// Code generated by Herebyfile.mjs generate:enums from internal/compiler/emitter.go. DO NOT EDIT.

export const enum EmitFlags {
    All = 0,
    OnlyJs = 1,
    OnlyDts = 2,
    OnlyForcedDts = 3,
}
