// Code generated by Herebyfile.mjs generate:enums from internal/compiler/emitter.go. DO NOT EDIT.
export var EmitFlags: any;
(function (EmitFlags) {
    EmitFlags[EmitFlags["All"] = 0] = "All";
    EmitFlags[EmitFlags["OnlyJs"] = 1] = "OnlyJs";
    EmitFlags[EmitFlags["OnlyDts"] = 2] = "OnlyDts";
    EmitFlags[EmitFlags["OnlyForcedDts"] = 3] = "OnlyForcedDts";
})(EmitFlags || (EmitFlags = {}));
