// Code generated by Herebyfile.mjs generate:enums from internal/spanmap/spanmap.go. DO NOT EDIT.
export var SpanMapPurpose: any;
(function (SpanMapPurpose) {
    SpanMapPurpose[SpanMapPurpose["None"] = 0] = "None";
    SpanMapPurpose[SpanMapPurpose["Semantic"] = 1] = "Semantic";
    SpanMapPurpose[SpanMapPurpose["Navigation"] = 2] = "Navigation";
    SpanMapPurpose[SpanMapPurpose["All"] = 3] = "All";
})(SpanMapPurpose || (SpanMapPurpose = {}));
