// Code generated by "stringer -type=Tristate -trimprefix=TS"; DO NOT EDIT.

package compiler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TSUnknown-0]
	_ = x[TSFalse-1]
	_ = x[TSTrue-2]
}

const _Tristate_name = "UnknownFalseTrue"

var _Tristate_index = [...]uint8{0, 7, 12, 16}

func (i Tristate) String() string {
	if i >= Tristate(len(_Tristate_index)-1) {
		return "Tristate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tristate_name[_Tristate_index[i]:_Tristate_index[i+1]]
}
