// Code generated by "stringer -type=ExportSyntax -output=parse_stringer_generated.go"; DO NOT EDIT.

package autoimport

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExportSyntaxNone-0]
	_ = x[ExportSyntaxModifier-1]
	_ = x[ExportSyntaxNamed-2]
	_ = x[ExportSyntaxDefaultModifier-3]
	_ = x[ExportSyntaxDefaultDeclaration-4]
	_ = x[ExportSyntaxEquals-5]
}

const _ExportSyntax_name = "ExportSyntaxNoneExportSyntaxModifierExportSyntaxNamedExportSyntaxDefaultModifierExportSyntaxDefaultDeclarationExportSyntaxEquals"

var _ExportSyntax_index = [...]uint8{0, 16, 36, 53, 80, 110, 128}

func (i ExportSyntax) String() string {
	if i < 0 || i >= ExportSyntax(len(_ExportSyntax_index)-1) {
		return "ExportSyntax(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExportSyntax_name[_ExportSyntax_index[i]:_ExportSyntax_index[i+1]]
}
