// Code generated by "stringer -type=ExportSyntax -output=parse_stringer_generated.go"; DO NOT EDIT.

package autoimport

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExportSyntaxModifier-0]
	_ = x[ExportSyntaxNamed-1]
	_ = x[ExportSyntaxDefaultModifier-2]
	_ = x[ExportSyntaxDefaultDeclaration-3]
	_ = x[ExportSyntaxEquals-4]
}

const _ExportSyntax_name = "ExportSyntaxModifierExportSyntaxNamedExportSyntaxDefaultModifierExportSyntaxDefaultDeclarationExportSyntaxEquals"

var _ExportSyntax_index = [...]uint8{0, 20, 37, 64, 94, 112}

func (i ExportSyntax) String() string {
	if i < 0 || i >= ExportSyntax(len(_ExportSyntax_index)-1) {
		return "ExportSyntax(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExportSyntax_name[_ExportSyntax_index[i]:_ExportSyntax_index[i+1]]
}
