# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

linters:
  disable-all: true
  enable:
    - nakedret
    # - whitespace
    # - staticcheck
    # - unparam
    # - unconvert
    # - prealloc
    # - errcheck

    # Maybe
    # - predeclared
    # - stylecheck
    # - wastedassign
    # - inamedparam
    # - revive
    # - gosec
    # - mirror
    # - gocritic

    # Maybe not
    # - dupword
    # - mnd
    # - unused
    # - gofumpt
    # - goconst

    # One day
    # - exhaustive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude:
    - '^could not import'
    - '^: #'
    - 'imported and not used$'
