# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: '2'

run:
  allow-parallel-runners: true

linters:
  default: none
  enable:
    # Enabled
    - asasalint
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - customlint
    - depguard
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - fatcontext
    - forbidigo
    - gocheckcompilerdirectives
    - goprintffuncname
    - govet
    - grouper
    - inamedparam
    - ineffassign
    - intrange
    - makezero
    - mirror
    - misspell
    - modernize
    - musttag
    - nakedret
    - nolintlint
    - paralleltest
    - perfsprint
    - predeclared
    - reassign
    - staticcheck
    - testableexamples
    - tparallel
    - unconvert
    - usestdlibvars
    - usetesting

    # Need to add headers
    # - goheader

    # Check
    # - exhaustive
    # - gocritic
    # - gosec
    # - revive
    # - testifylint
    # - unparam
    # - unused

  settings:
    custom:
      customlint:
        type: module

    depguard:
      rules:
        main:
          deny:
            - pkg: 'encoding/json$'
              desc: 'Use "github.com/microsoft/typescript-go/internal/json" instead.'
            - pkg: 'github.com/go-json-experiment/json'
              desc: 'Use "github.com/microsoft/typescript-go/internal/json" instead.'

    forbidigo:
      analyze-types: true
      forbid:
        - pattern: '.*'
          msg: tspath should likely be used instead
          pkg: ^(path|path/filepath)$
        - pattern: '.*'
          msg: a host implementation should likely be used instead
          pkg: ^os(/|$)
        - pattern: 'GOOS'
          msg: a host implementation should likely be used instead
          pkg: ^runtime$

    staticcheck:
      checks:
        - all
        - -QF1001 # Apply De Morgan’s law
        - -QF1003 # Convert if/else-if chain to tagged switch
        - -SA1019 # Using a deprecated function, variable, constant or field
        - -SA9003 # Empty body in an if or else branch
        - -ST1000 # Incorrect or missing package comment
        - -ST1003 # Poorly chosen identifier
        - -ST1006 # Poorly chosen receiver name
        - -ST1016 # Use consistent method receiver names
        - -ST1020 # The documentation of an exported function should start with the function’s name
        - -ST1021 # The documentation of an exported type should start with type’s name
        - -ST1022 # The documentation of an exported variable or constant should start with variable’s name

  exclusions:
    rules:
      - path: internal/fourslash/tests/gen/
        linters:
          - misspell
      - path: 'internal/(repo|testutil|testrunner|vfs|pprof|execute/tsctests|bundled)|cmd/tsgo'
        text: should likely be used instead
      - path: '(.+)_test\.go$'
        text: should likely be used instead
      - path: '_tools'
        text: should likely be used instead

    presets:
      - comments
      - std-error-handling

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
