# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

linters:
  disable-all: true
  enable:
    # Enabled
    - asasalint
    - inamedparam
    - nakedret
    - govet
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - fatcontext
    - gci
    - gocheckcompilerdirectives
    - goprintffuncname
    - gosimple
    - grouper
    - ineffassign
    - intrange
    - makezero
    - mirror
    - musttag
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - reassign
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - whitespace
    - wrapcheck

    # Need to add headers
    # - goheader

    # Check
    # - exhaustive
    # - goconst
    # - gocritic
    # - gosec
    # - predeclared
    # - revive
    # - staticcheck
    # - stylecheck
    # - testifylint
    # - unparam
    # - unused

# linters-settings:
#   revive:
#     enable-all-rules: true
#     rules:
#       - name: unused-parameter
#         disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude:
    - '^could not import'
    - '^: #'
    - 'imported and not used$'
