// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tscWatch_commandLineWatch_watch_detects_file_added_in_multiple_new_subdirectories_simultaneously(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLineWatch",
		SubScenario:     "watch detects file added in multiple new subdirectories simultaneously",
		CommandLineArgs: []string{"--watch"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/src/a.ts": "export const a = 1;",
			"/home/src/workspaces/project/tsconfig.json": `{
	"compilerOptions": {},
	"include": ["src/**/*.ts"]
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "create multiple new subdirs with files",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/models/user.ts", "export interface User { name: string; }")
			sys.WriteFile("/home/src/workspaces/project/src/utils/format.ts", "export function format(s: string): string { return s.trim(); }")
		},
	})
	test.End()
}
