// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_ignoreConfig_specifying_files_with_ignoreConfig(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "ignoreConfig",
		SubScenario:     "specifying files with --ignoreConfig",
		CommandLineArgs: []string{"src/a.ts", "--ignoreConfig"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/c.ts":     "export const c = 10;",
			"/home/src/workspaces/project/src/a.ts": "export const a = 10;",
			"/home/src/workspaces/project/src/b.ts": "export const b = 10;",
			"/home/src/workspaces/project/tsconfig.json": `{
    "include": ["src"],
}`,
		},
	}
	test.Start(t)
	test.End()
}
