// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_declarationEmit_when_using_Windows_paths_and_uppercase_letters(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:         "declarationEmit",
		SubScenario:      "when using Windows paths and uppercase letters",
		CommandLineArgs:  []string{"-p", "D:\\Work\\pkg1", "--explainFiles"},
		Cwd:              "D:/Work/pkg1",
		IgnoreCase:       true,
		WindowsStyleRoot: "D:/",
		Files: tsctests.FileMap{
			"D:/Work/pkg1/package.json": `{
    "name": "ts-specifier-bug",
    "version": "1.0.0",
    "main": "index.js"
}`,
			"D:/Work/pkg1/src/main.ts": `import { PartialType } from './utils';

class Common {}

export class Sub extends PartialType(Common) {
    id: string;
}`,
			"D:/Work/pkg1/src/utils/index.ts": `import { MyType, MyReturnType } from './type-helpers';

export function PartialType<T>(classRef: MyType<T>) {
    abstract class PartialClassType {
        constructor() {}
    }

    return PartialClassType as MyReturnType;
}`,
			"D:/Work/pkg1/src/utils/type-helpers.ts": `export type MyReturnType = {	
    new (...args: any[]): any;
};

export interface MyType<T = any> extends Function {
    new (...args: any[]): T;
}`,
			"D:/Work/pkg1/tsconfig.json": `{
    "compilerOptions": {
        "declaration": true,
        "target": "es2017",
        "outDir": "./dist",
    },
    "include": ["src"],
}`,
		},
	}
	test.Start(t)
	test.End()
}
