// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_projectReferences_errors_when_the_referenced_project_doesnt_have_composite(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "projectReferences",
		SubScenario:     "errors when the referenced project doesnt have composite",
		CommandLineArgs: []string{"--p", "reference/tsconfig.json"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/primary/a.ts": "export { };",
			"/home/src/workspaces/project/primary/tsconfig.json": `{
    "compilerOptions": {
        "composite": false,
        "outDir": "bin",
    }
}`,
			"/home/src/workspaces/project/reference/b.ts": "import * as mod_1 from \"../primary/a\";",
			"/home/src/workspaces/project/reference/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "outDir": "bin",
    },
    "files": [ "b.ts" ],
    "references": [ { "path": "../primary" } ]
}`,
		},
	}
	test.Start(t)
	test.End()
}
