// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_showConfig_Show_TSConfig_with_advanced_options(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "showConfig",
		SubScenario:     "Show TSConfig with advanced options",
		CommandLineArgs: []string{"--showConfig", "--declaration", "--declarationDir", "lib", "--skipLibCheck", "--noErrorTruncation"},
	}
	test.Start(t)
	test.End()
}
