// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuildWatch_programUpdates_declarationEmitErrors_introduceError_when_file_with_no_error_changes(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "programUpdates",
		SubScenario:     "declarationEmitErrors introduceError when file with no error changes",
		CommandLineArgs: []string{"-b", "-w", "app"},
		Cwd:             "/user/username/projects/solution",
		Files: tsctests.FileMap{
			"/user/username/projects/solution/app/fileWithError.ts": `export var myClassWithError = class {
    tags() { }

};`,
			"/user/username/projects/solution/app/fileWithoutError.ts": "export class myClass { }",
			"/user/username/projects/solution/app/tsconfig.json": `{
    "compilerOptions": {
        "composite": true
    }
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "Introduce error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/solution/app/fileWithError.ts", `export var myClassWithError = class {
    tags() { }
    private p = 12
};`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Change fileWithoutError",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/solution/app/fileWithoutError.ts", "export class myClass2 { }")
		},
	})
	test.End()
}
