// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_projectReferences_default_import_interop_uses_referenced_project_settings(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "projectReferences",
		SubScenario:     "default import interop uses referenced project settings",
		CommandLineArgs: []string{"--p", "app", "--pretty", "false"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/app/src/index.ts": `import local from "./local"; // Error
import esm from "esm-package"; // Error
import referencedSource from "../../lib/src/a"; // Error
import referencedDeclaration from "../../lib/dist/a"; // Error
import ambiguous from "ambiguous-package"; // Ok`,
			"/home/src/workspaces/project/app/src/local.ts": "export const local = 0;",
			"/home/src/workspaces/project/app/tsconfig.json": `{
    "compilerOptions": {
        "module": "esnext",
        "moduleResolution": "bundler",
        "rootDir": "src",
        "outDir": "dist",
    },
    "include": ["src"],
    "references": [
        { "path": "../lib" },
    ],
}`,
			"/home/src/workspaces/project/lib/dist/a.d.ts": "export declare const a = 0;",
			"/home/src/workspaces/project/lib/src/a.ts":    "export const a = 0;",
			"/home/src/workspaces/project/lib/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "declaration": true,
        "rootDir": "src",
        "outDir": "dist",
        "module": "esnext",
        "moduleResolution": "bundler",
    },
    "include": ["src"],
}`,
			"/home/src/workspaces/project/node_modules/ambiguous-package/index.d.ts": "export declare const ambiguous: number;",
			"/home/src/workspaces/project/node_modules/ambiguous-package/package.json": `{
    "name": "ambiguous-package"
}`,
			"/home/src/workspaces/project/node_modules/esm-package/index.d.ts": "export declare const esm: number;",
			"/home/src/workspaces/project/node_modules/esm-package/package.json": `{
    "name": "esm-package",
    "type": "module"
}`,
		},
	}
	test.Start(t)
	test.End()
}
