// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_incremental_react_jsx_emit_mode_with_no_backing_types_found_doesnt_crash_under_strict(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "incremental",
		SubScenario:     "react-jsx-emit-mode with no backing types found doesnt crash under --strict",
		CommandLineArgs: []string{"--strict"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/node_modules/@types/react/index.d.ts": `export {};
declare global {
    namespace JSX {
        interface Element {}
        interface IntrinsicElements {
            div: {
                propA?: boolean;
            };
        }
    }
}`,
			"/home/src/workspaces/project/node_modules/react/jsx-runtime.js": "export {}",
			"/home/src/workspaces/project/src/index.tsx":                     "export const App = () => <div propA={true}></div>;",
			"/home/src/workspaces/project/tsconfig.json": `{ 
    "compilerOptions": { 
        "module": "commonjs",
        "jsx": "react-jsx", 
        "incremental": true, 
        "jsxImportSource": "react" 
    } 
}`,
		},
	}
	test.Start(t)
	test.End()
}
