// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_generateTrace_generateTrace_with_multiple_files_and_complex_types(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "generateTrace",
		SubScenario:     "generateTrace with multiple files and complex types",
		CommandLineArgs: []string{"--generateTrace", "/home/src/workspaces/project/trace", "--singleThreaded"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/main.ts": `import { Container, Nullable } from "./types";
const c: Container<number> = { value: 42, map: (fn) => ({ value: fn(42), map: c.map }) };
const n: Nullable<string> = "hello";`,
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "strict": true,
        "noEmit": true
    }
}`,
			"/home/src/workspaces/project/types.ts": `export interface Container<T> {
    value: T;
    map<U>(fn: (x: T) => U): Container<U>;
}
export type Nullable<T> = T | null | undefined;`,
		},
	}
	test.Start(t)
	test.End()
}
