// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_declarationEmit_when_inferred_export_should_reuse_imported_type_alias_across_a_module_boundary(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "declarationEmit",
		SubScenario:     "when inferred export should reuse imported type alias across a module boundary",
		CommandLineArgs: []string{"--p", "tsconfig.json"},
		Files: tsctests.FileMap{
			"/home/src/tslibs/TS/Lib/lib.es2022.full.d.ts": `/// <reference no-default-lib="true"/>
interface Boolean {}
interface Function {}
interface CallableFunction {}
interface NewableFunction {}
interface IArguments {}
interface Number { toExponential: any; }
interface Object {}
interface RegExp {}
interface String { charAt: any; }
interface Array<T> { length: number; [n: number]: T; }
interface ReadonlyArray<T> {}
interface SymbolConstructor {
    (desc?: string | number): symbol;
    for(name: string): symbol;
    readonly toStringTag: symbol;
}
declare var Symbol: SymbolConstructor;
interface Symbol {
    readonly [Symbol.toStringTag]: string;
}
declare const console: { log(msg: any): void; };
type Partial<T> = {
    [K in keyof T]?: T[K];
};`,
			"/home/src/workspaces/project/a.ts": `interface ISettings {
    age: number;
}

export type Settings = Partial<ISettings>;`,
			"/home/src/workspaces/project/factory.ts": `import type { Settings } from "./a";

export const makeObj = () => ({
    fn: (s?: Settings): Settings | undefined => s,
});`,
			"/home/src/workspaces/project/state.ts": `import { makeObj } from "./factory";

export const obj = makeObj();`,
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "strict": true,
        "declaration": true,
        "emitDeclarationOnly": true,
        "target": "es2022",
        "module": "esnext",
    },
    "files": ["./a.ts", "./factory.ts", "./state.ts"],
}`,
		},
	}
	test.Start(t)
	test.End()
}
