// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuild_noEmit_dts_errors_with_declaration_enable_changes_with_incremental_as_modules(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "noEmit",
		SubScenario:     "dts errors with declaration enable changes with incremental as modules",
		CommandLineArgs: []string{"-b", "-v", "--noEmit"},
		Cwd:             "/home/src/projects/project",
		Files: tsctests.FileMap{
			"/home/src/projects/project/a.ts": "export const a = class { private p = 10; };",
			"/home/src/projects/project/b.ts": "export const b = 10;",
			"/home/src/projects/project/tsconfig.json": `{
    "compilerOptions": {
        "incremental": true,
    }
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "With declaration enabled noEmit - Should report errors",
		CommandLineArgs: []string{"-b", "-v", "--noEmit", "--declaration"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "With declaration and declarationMap noEmit - Should report errors",
		CommandLineArgs: []string{"-b", "-v", "--noEmit", "--declaration", "--declarationMap"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "Dts Emit with error",
		CommandLineArgs: []string{"-b", "-v", "--declaration"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Fix the error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/projects/project/a.ts", "export const a = class { public p = 10; };")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "With declaration enabled noEmit",
		CommandLineArgs: []string{"-b", "-v", "--noEmit", "--declaration"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "With declaration and declarationMap noEmit",
		CommandLineArgs: []string{"-b", "-v", "--noEmit", "--declaration", "--declarationMap"},
	})
	test.End()
}
