// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuildWatch_moduleResolution_handles_the_cache_correctly_when_two_projects_use_different_module_resolution_settings(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "moduleResolution",
		SubScenario:     "handles the cache correctly when two projects use different module resolution settings",
		CommandLineArgs: []string{"--b", "-w", "-v"},
		Cwd:             "/user/username/projects/myproject",
		Files: tsctests.FileMap{
			"/user/username/projects/myproject/node_modules/@types/bar/index.d.ts":    "export const bar = 10;",
			"/user/username/projects/myproject/node_modules/@types/foo/index.d.ts":    "export const foo = 10;",
			"/user/username/projects/myproject/project1/index.ts":                     "import { foo } from \"file\";",
			"/user/username/projects/myproject/project1/node_modules/file/index.d.ts": "export const foo = 10;",
			"/user/username/projects/myproject/project1/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "types": ["foo", "bar"]
    },
    "files": ["index.ts"],
}`,
			"/user/username/projects/myproject/project2/index.ts":                     "import { foo } from \"file\";",
			"/user/username/projects/myproject/project2/node_modules/file/index.d.ts": "export const foo = 10;",
			"/user/username/projects/myproject/project2/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "types": ["foo"],
        "module": "nodenext",
        "moduleResolution": "nodenext"
    },
    "files": ["index.ts"],
}`,
			"/user/username/projects/myproject/tsconfig.json": `{
     "files": [],
     "references": [
         { "path": "./project1" },
         { "path": "./project2" },
     ],
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "Append text",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/myproject/project1/index.ts", "import { foo } from \"file\";const bar = 10;")
		},
	})
	test.End()
}
