// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
	"github.com/microsoft/typescript-go/internal/vfs/vfstest"
)

func Test_tsbuild_inferredTypeFromMonorepoReference_inferred_type_from_referenced_project_that_references_another_project_in_monorepo(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "inferredTypeFromMonorepoReference",
		SubScenario:     "inferred type from referenced project that references another project in monorepo",
		CommandLineArgs: []string{"--b", "--verbose"},
		Cwd:             "/home/src/workspaces/solution",
		Files: tsctests.FileMap{
			"/home/src/workspaces/solution/node_modules/package-a": vfstest.Symlink("/home/src/workspaces/solution/packages/package-a"),
			"/home/src/workspaces/solution/node_modules/package-b": vfstest.Symlink("/home/src/workspaces/solution/packages/package-b"),
			"/home/src/workspaces/solution/node_modules/package-c": vfstest.Symlink("/home/src/workspaces/solution/packages/package-c"),
			"/home/src/workspaces/solution/package.json": `{
    "name": "tsgo-monorepo-issue",
    "private": true,
    "workspaces": ["packages/*"]
}`,
			"/home/src/workspaces/solution/packages/package-a/package.json": `{
    "name": "package-a",
    "version": "1.0.0",
    "private": true,
    "type": "module",
    "main": "./src/index.ts",
    "types": "./src/index.ts",
    "exports": {
        ".": "./src/index.ts"
    },
    "dependencies": {
        "package-b": "workspace:*"
    }
}`,
			"/home/src/workspaces/solution/packages/package-a/src/index.ts": `import { createThing } from "package-b";

class MyClass {
    public thing = createThing({ id: "1", name: "test", enabled: true });
}

export { MyClass };`,
			"/home/src/workspaces/solution/packages/package-a/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "declaration": true,
        "emitDeclarationOnly": true,
        "module": "ESNext",
        "moduleResolution": "Bundler",
        "target": "ES2022",
        "outDir": "./out",
        "rootDir": "./src"
    },
    "include": ["src/**/*"],
    "references": [{ "path": "../package-b" }]
}`,
			"/home/src/workspaces/solution/packages/package-b/package.json": `{
    "name": "package-b",
    "version": "1.0.0",
    "private": true,
    "type": "module",
    "main": "./src/index.ts",
    "types": "./src/index.ts",
    "exports": {
        ".": "./src/index.ts"
    },
    "dependencies": {
        "package-c": "workspace:*"
    }
}`,
			"/home/src/workspaces/solution/packages/package-b/src/index.ts": `import type { MyType } from "package-c";

export function createThing(input: MyType): MyType {
    return { ...input };
}`,
			"/home/src/workspaces/solution/packages/package-b/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "declaration": true,
        "emitDeclarationOnly": true,
        "module": "ESNext",
        "moduleResolution": "Bundler",
        "target": "ES2022",
        "outDir": "./out",
        "rootDir": "./src"
    },
    "include": ["src/**/*"],
    "references": [{ "path": "../package-c" }]
}`,
			"/home/src/workspaces/solution/packages/package-c/package.json": `{
    "name": "package-c",
    "version": "1.0.0",
    "private": true,
    "type": "module",
    "main": "./src/index.ts",
    "types": "./src/index.ts",
    "exports": {
        ".": "./src/index.ts"
    }
}`,
			"/home/src/workspaces/solution/packages/package-c/src/index.ts": `export interface MyType {
    id: string;
    name: string;
    enabled: boolean;
}`,
			"/home/src/workspaces/solution/packages/package-c/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "declaration": true,
        "emitDeclarationOnly": true,
        "module": "ESNext",
        "moduleResolution": "Bundler",
        "target": "ES2022",
        "outDir": "./out",
        "rootDir": "./src"
    },
    "include": ["src/**/*"]
}`,
			"/home/src/workspaces/solution/tsconfig.json": `{
    "files": [],
    "include": [],
    "references": [
        { "path": "packages/package-a" },
        { "path": "packages/package-b" },
        { "path": "packages/package-c" }
    ]
}`,
		},
	}
	test.Start(t)
	test.End()
}
