// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_projectReferences_doesnt_infer_the_rootDir_from_source_paths(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "projectReferences",
		SubScenario:     "doesnt infer the rootDir from source paths",
		CommandLineArgs: []string{"--p", "alpha/tsconfig.json"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/alpha/src/a.ts": "export const m: number = 3;",
			"/home/src/workspaces/project/alpha/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "outDir": "bin",
    },
    "references": []
}`,
		},
	}
	test.Start(t)
	test.End()
}
