// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuild_moduleResolution_resolution_from_d_ts_of_referenced_project(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "moduleResolution",
		SubScenario:     "resolution from d.ts of referenced project",
		CommandLineArgs: []string{"--b", "consumer", "--traceResolution", "-v"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/common.d.ts": "export type OnValue = (value: number) => void",
			"/home/src/workspaces/project/consumer/index.ts": `import { ValueProducerDeclaration, ValueProducerFromTs } from "@producer"
declare let v: ValueProducerDeclaration;
// n is implicitly any because onValue is actually any (despite what the tooltip says)
v.onValue = (n) => {
}
// n is implicitly number as expected
declare let v2: ValueProducerFromTs;
v2.onValue = (n) => {
}`,
			"/home/src/workspaces/project/consumer/tsconfig.json": `{
    "compilerOptions": {
        "strict": true,
        "module": "nodenext",
        "moduleResolution": "nodenext",
        "paths": {
            "@producer": ["../producer/index"],
        },
    },
    "references": [
        { "path": "../producer" },
    ],
}`,
			"/home/src/workspaces/project/producer/in-js.d.ts": `import { OnValue } from "@common"
export interface ValueProducerDeclaration {
    onValue: OnValue;
}`,
			"/home/src/workspaces/project/producer/index.ts": `export { ValueProducerDeclaration } from "./in-js"
import { OnValue } from "@common"
export interface ValueProducerFromTs {
    onValue: OnValue;
}`,
			"/home/src/workspaces/project/producer/tsconfig.json": `{
    "compilerOptions": {
        "strict": true,
        "composite": true,
        "module": "nodenext",
        "moduleResolution": "nodenext",
        "paths": {
            "@common": ["../common.d.ts"],
        },
    },
}`,
		},
	}
	test.Start(t)
	test.End()
}
