// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuildWatch_programUpdates_works_with_extended_source_files(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "programUpdates",
		SubScenario:     "works with extended source files",
		CommandLineArgs: []string{"-b", "-w", "-v", "project1.tsconfig.json", "project2.tsconfig.json", "project3.tsconfig.json"},
		Cwd:             "/user/username/projects/project",
		Files: tsctests.FileMap{
			"/user/username/projects/project/alpha.tsconfig.json": "{}",
			"/user/username/projects/project/bravo.tsconfig.json": `{
    "extends": "./alpha.tsconfig.json",
}`,
			"/user/username/projects/project/commonFile1.ts": "let x = 1",
			"/user/username/projects/project/commonFile2.ts": "let y = 1",
			"/user/username/projects/project/extendsConfig1.tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
    },
}`,
			"/user/username/projects/project/extendsConfig2.tsconfig.json": `{
    "compilerOptions": {
        "strictNullChecks": false,
    },
}`,
			"/user/username/projects/project/extendsConfig3.tsconfig.json": `{
    "compilerOptions": {
        "noImplicitAny": true,
    },
}`,
			"/user/username/projects/project/other.ts":  "let z = 0;",
			"/user/username/projects/project/other2.ts": "let k = 0;",
			"/user/username/projects/project/project1.tsconfig.json": `{
    "extends": "./alpha.tsconfig.json",
    "compilerOptions": {
        "composite": true,
    },
    "files": ["commonFile1.ts", "commonFile2.ts"],
}`,
			"/user/username/projects/project/project2.tsconfig.json": `{
    "extends": "./bravo.tsconfig.json",
    "compilerOptions": {
        "composite": true,
    },
    "files": ["other.ts"],
}`,
			"/user/username/projects/project/project3.tsconfig.json": `{
    "extends": [
        "./extendsConfig1.tsconfig.json",
        "./extendsConfig2.tsconfig.json",
        "./extendsConfig3.tsconfig.json",
    ],
    "compilerOptions": {
        "composite": false,
    },
    "files": ["other2.ts"],
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "Modify alpha config",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/project/alpha.tsconfig.json", `{
    "compilerOptions": {
        "strict": true
    }
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "change bravo config",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/project/bravo.tsconfig.json", `{
    "extends": "./alpha.tsconfig.json",
    "compilerOptions": { "strict": false }
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "project 2 extends alpha",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/project/project2.tsconfig.json", `{
    "extends": "./alpha.tsconfig.json",
    "files": ["other.ts"]
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "update aplha config",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/project/alpha.tsconfig.json", "{}")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Modify extendsConfigFile2",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/project/extendsConfig2.tsconfig.json", `{
    "compilerOptions": { "strictNullChecks": true }
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Modify project 3",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/project/project3.tsconfig.json", `{
    "extends": ["./extendsConfig1.tsconfig.json", "./extendsConfig2.tsconfig.json"],
    "compilerOptions": { "composite": false },
    "files": ["other2.ts"],
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Delete extendedConfigFile2 and report error",
		Edit: func(sys *tsctests.TestSys) {
			sys.Remove("/user/username/projects/project/extendsConfig2.tsconfig.json")
		},
	})
	test.End()
}
