// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_incremental_when_passing_rootDir_from_commandline(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "incremental",
		SubScenario:     "when passing rootDir from commandline",
		CommandLineArgs: []string{"--rootDir", "src"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/src/main.ts": "export const x = 10;",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "incremental": true,
        "outDir": "dist"
    }
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})
	test.End()
}
