// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuildWatch_programUpdates_declarationEmitErrors_when_fixing_error_files_all_files_are_emitted(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "programUpdates",
		SubScenario:     "declarationEmitErrors when fixing error files all files are emitted",
		CommandLineArgs: []string{"-b", "-w", "app"},
		Cwd:             "/user/username/projects/solution",
		Files: tsctests.FileMap{
			"/user/username/projects/solution/app/fileWithError.ts": `export var myClassWithError = class {
    tags() { }
    private p = 12
};`,
			"/user/username/projects/solution/app/fileWithoutError.ts": "export class myClass { }",
			"/user/username/projects/solution/app/tsconfig.json": `{
    "compilerOptions": {
        "composite": true
    }
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "Fix error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/solution/app/fileWithError.ts", `export var myClassWithError = class {
    tags() { }
    
};`)
		},
	})
	test.End()
}
