// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tscWatch_commandLineWatch_watch_detects_import_path_restructured(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLineWatch",
		SubScenario:     "watch detects import path restructured",
		CommandLineArgs: []string{"--watch"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/index.ts":      "import { util } from \"./lib/util\";",
			"/home/src/workspaces/project/lib/util.ts":   "export const util = \"v1\";",
			"/home/src/workspaces/project/tsconfig.json": "{}",
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "move file to new path and update import",
		Edit: func(sys *tsctests.TestSys) {
			sys.Remove("/home/src/workspaces/project/lib/util.ts")
			sys.WriteFile("/home/src/workspaces/project/index.ts", "import { util } from \"./src/util\";")
			sys.WriteFile("/home/src/workspaces/project/src/util.ts", "export const util = \"v2\";")
		},
	})
	test.End()
}
