// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuild_projectReferenceWithRootDirInParent_reports_error_for_same_tsbuildinfo_file(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "projectReferenceWithRootDirInParent",
		SubScenario:     "reports error for same tsbuildinfo file",
		CommandLineArgs: []string{"--b", "src/main", "--verbose"},
		Cwd:             "/home/src/workspaces/solution",
		Files: tsctests.FileMap{
			"/home/src/workspaces/solution/src/main/a.ts": `import { b } from './b';
const a = b;`,
			"/home/src/workspaces/solution/src/main/b.ts": "export const b = 0;",
			"/home/src/workspaces/solution/src/main/tsconfig.json": `{
    "compilerOptions": { "composite": true, "outDir": "../../dist/" },
    "references": [{ "path": "../other" }]
}`,
			"/home/src/workspaces/solution/src/other/other.ts": "export const Other = 0;",
			"/home/src/workspaces/solution/src/other/tsconfig.json": `{
    "compilerOptions": { "composite": true, "outDir": "../../dist/" },
}`,
			"/home/src/workspaces/solution/tsconfig.base.json": `{
    "compilerOptions": {
        "composite": true,
        "declaration": true,
        "rootDir": "./src/",
        "outDir": "./dist/",
        "skipDefaultLibCheck": true,
    },
    "exclude": [
        "node_modules",
    ],
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})
	test.End()
}
