// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tscWatch_commandLineWatch_watch_with_no_tsconfig(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLineWatch",
		SubScenario:     "watch with no tsconfig",
		CommandLineArgs: []string{"index.ts", "--watch"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/index.ts": "",
		},
	}
	test.Start(t)
	test.End()
}
