// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_commandLine_show_help_with_ExitStatus_DiagnosticsPresent_OutputsSkipped(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:    "commandLine",
		SubScenario: "show help with ExitStatus.DiagnosticsPresent_OutputsSkipped",
		Env: map[string]string{
			"TS_TEST_TERMINAL_WIDTH": "120",
		},
	}
	test.Start(t)
	test.End()
}
