// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuild_commandLine_locale(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLine",
		SubScenario:     "locale",
		CommandLineArgs: []string{"--build", "--help", "--locale", "en"},
	}
	test.Start(t)
	test.End()
}
