// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_noEmit_when_project_has_strict_true(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "noEmit",
		SubScenario:     "when project has strict true",
		CommandLineArgs: []string{"--noEmit"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/class1.ts": "export class class1 {}",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "incremental": true,
        "strict": true
    }
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})
	test.End()
}
