// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuildWatch_reexport_Reports_errors_correctly(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "reexport",
		SubScenario:     "Reports errors correctly",
		CommandLineArgs: []string{"-b", "-w", "-verbose", "src"},
		Cwd:             "/user/username/projects/reexport",
		Files: tsctests.FileMap{
			"/user/username/projects/reexport/src/main/index.ts": `import { Session } from "../pure";

export const session: Session = {
    foo: 1
};`,
			"/user/username/projects/reexport/src/main/tsconfig.json": `{
    "compilerOptions": {
        "outDir": "../../out",
        "rootDir": "../",
    },
    "include": ["**/*.ts"],
    "references": [{ "path": "../pure" }],
}`,
			"/user/username/projects/reexport/src/pure/index.ts": "export * from \"./session\";",
			"/user/username/projects/reexport/src/pure/session.ts": `export interface Session {
    foo: number;
    // bar: number;
}`,
			"/user/username/projects/reexport/src/pure/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "outDir": "../../out",
        "rootDir": "../",
    },
    "include": ["**/*.ts"],
}`,
			"/user/username/projects/reexport/src/tsconfig.json": `{
    "files": [],
    "include": [],
    "references": [{ "path": "./pure" }, { "path": "./main" }],
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "Introduce error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/reexport/src/pure/session.ts", `export interface Session {
    foo: number;
    bar: number;
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Fix error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/reexport/src/pure/session.ts", `export interface Session {
    foo: number;
    // bar: number;
}`)
		},
	})
	test.End()
}
