// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuild_resolveJsonModule_include_of_json_along_with_other_include_and_file_name_matches_ts_file_non_composite(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "resolveJsonModule",
		SubScenario:     "include of json along with other include and file name matches ts file non-composite",
		CommandLineArgs: []string{"--b", "project", "--v", "--explainFiles", "--listEmittedFiles"},
		Cwd:             "/home/src/workspaces/solution",
		Files: tsctests.FileMap{
			"/home/src/workspaces/solution/project/src/index.json": `{
    "hello": "world"
}`,
			"/home/src/workspaces/solution/project/src/index.ts": `import hello from "./index.json"
export default hello.hello`,
			"/home/src/workspaces/solution/project/tsconfig.json": `{
    "compilerOptions": {
        "composite": false,
        "module": "commonjs",
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "outDir": "dist",
        "skipDefaultLibCheck": true,

    },
    "include": [ "src/**/*", "src/**/*.json" ],
}`,
		},
	}
	test.Start(t)
	test.End()
}
