// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tscWatch_commandLineWatch_watch_handles_tsconfig_deleted(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLineWatch",
		SubScenario:     "watch handles tsconfig deleted",
		CommandLineArgs: []string{"--watch"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/index.ts":      "const x = 1;",
			"/home/src/workspaces/project/tsconfig.json": "{}",
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption:      "delete tsconfig",
		ExpectedDiff: "incremental reports config read error while clean build without tsconfig prints usage help",
		Edit: func(sys *tsctests.TestSys) {
			sys.Remove("/home/src/workspaces/project/tsconfig.json")
		},
	})
	test.End()
}
