// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_commandLine_Parse_p(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLine",
		SubScenario:     "Parse -p",
		CommandLineArgs: []string{"-p", "."},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/first.ts": "export const a = 1",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "strict": true,
        "noEmit": true
    }
}`,
		},
	}
	test.Start(t)
	test.End()
}
