// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_showConfig_Show_TSConfig_with_exclude_and_outDir(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "showConfig",
		SubScenario:     "Show TSConfig with exclude and outDir",
		CommandLineArgs: []string{"-p", "tsconfig.json", "--showConfig"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/src/bin/tool.ts": "export const b = 2;",
			"/home/src/workspaces/project/src/index.ts":    "export const a = 1;",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "strict": true,
        "outDir": "./build"
    },
    "exclude": [
        "build"
    ]
}`,
		},
	}
	test.Start(t)
	test.End()
}
