// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_commandLine_Initialized_TSConfig_with_help(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLine",
		SubScenario:     "Initialized TSConfig with --help",
		CommandLineArgs: []string{"--init", "--help"},
	}
	test.Start(t)
	test.End()
}
