// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuildWatch_extends_configDir_template(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "extends",
		SubScenario:     "configDir template",
		CommandLineArgs: []string{"--b", "-w", "--explainFiles", "--v"},
		Cwd:             "/home/src/projects/myproject",
		Files: tsctests.FileMap{
			"/home/src/projects/configs/first/tsconfig.json": `{
    "extends": "../second/tsconfig.json",
    "include": ["${configDir}/src"],
    "compilerOptions": {
        "typeRoots": ["root1", "${configDir}/root2", "root3"],
        "types": [],
    },
}`,
			"/home/src/projects/configs/second/tsconfig.json": `{
    "files": ["${configDir}/main.ts"],
    "compilerOptions": {
        "declarationDir": "${configDir}/decls",
        "paths": {
            "@myscope/*": ["${configDir}/types/*"],
        },
    },
    "watchOptions": {
        "excludeFiles": ["${configDir}/main.ts"],
    },
}`,
			"/home/src/projects/myproject/main.ts": `// some comment
export const y = 10;
import { x } from "@myscope/sometype";`,
			"/home/src/projects/myproject/tsconfig.json": `{
    "extends": "../configs/first/tsconfig.json",
    "compilerOptions": {
        "declaration": true,
        "outDir": "outDir",
        "traceResolution": true,
    },
}`,
			"/home/src/projects/myproject/types/sometype.ts": "export const x = 10;",
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "edit extended config file",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/projects/configs/first/tsconfig.json", `{
    "extends": "../second/tsconfig.json",
    "include": ["${configDir}/src"],
    "compilerOptions": {
        "typeRoots": ["${configDir}/root2"],
        "types": [],
    },
}`)
		},
	})
	test.End()
}
