// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_libraryResolution_when_noLib_toggles(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:    "libraryResolution",
		SubScenario: "when noLib toggles",
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/a.d.ts": "declare const a = \"hello\";",
			"/home/src/workspaces/project/b.ts":   "const b = 10;",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "declaration": true,
        "incremental": true,
        "lib": ["es6"],
    },
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption:         "with --noLib",
		CommandLineArgs: []string{"--noLib"},
	})
	test.End()
}
