// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_projectReferences_importing_const_enum_from_referenced_project_with_preserveConstEnums_and_verbatimModuleSyntax(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "projectReferences",
		SubScenario:     "importing const enum from referenced project with preserveConstEnums and verbatimModuleSyntax",
		CommandLineArgs: []string{"--p", "project", "--pretty", "false"},
		Cwd:             "/home/src/workspaces/solution",
		Files: tsctests.FileMap{
			"/home/src/workspaces/solution/no-preserve/index.d.ts": "export declare const enum F { A = 1 }",
			"/home/src/workspaces/solution/no-preserve/index.ts":   "export const enum E { A = 1 }",
			"/home/src/workspaces/solution/no-preserve/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "declaration": true,
        "preserveConstEnums": false,
    },
}`,
			"/home/src/workspaces/solution/preserve/index.d.ts": "export declare const enum E { A = 1 }",
			"/home/src/workspaces/solution/preserve/index.ts":   "export const enum E { A = 1 }",
			"/home/src/workspaces/solution/preserve/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "declaration": true,
        "preserveConstEnums": true,
    },
}`,
			"/home/src/workspaces/solution/project/index.ts": `import { E } from "../preserve";
import { F } from "../no-preserve";
E.A;
F.A;`,
			"/home/src/workspaces/solution/project/tsconfig.json": `{
    "compilerOptions": {
        "module": "preserve",
        "verbatimModuleSyntax": true,
    },
    "references": [
        { "path": "../preserve" },
        { "path": "../no-preserve" },
    ],
}`,
		},
	}
	test.Start(t)
	test.End()
}
