// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_commandLine_help_all(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLine",
		SubScenario:     "help all",
		CommandLineArgs: []string{"--help", "--all"},
	}
	test.Start(t)
	test.End()
}
