// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_forceConsistentCasingInFileNames_when_file_is_included_from_multiple_places_with_different_casing(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "forceConsistentCasingInFileNames",
		SubScenario:     "when file is included from multiple places with different casing",
		CommandLineArgs: []string{"--explainFiles"},
		Cwd:             "/home/src/projects/project",
		IgnoreCase:      true,
		Files: tsctests.FileMap{
			"/home/src/projects/project/node_modules/fp-ts/lib/struct.d.ts": "export function foo(): void",
			"/home/src/projects/project/src/anotherFile.ts": `import * as xs1 from "fp-ts/lib/Struct";
import * as xs2 from "fp-ts/lib/struct";
import * as xs3 from "./Struct";
import * as xs4 from "./struct";`,
			"/home/src/projects/project/src/oneMore.ts": `import * as xs1 from "fp-ts/lib/Struct";
import * as xs2 from "fp-ts/lib/struct";
import * as xs3 from "./Struct";
import * as xs4 from "./struct";`,
			"/home/src/projects/project/src/struct.d.ts": `import * as xs1 from "fp-ts/lib/Struct";
import * as xs2 from "fp-ts/lib/struct";
import * as xs3 from "./Struct";
import * as xs4 from "./struct";`,
			"/home/src/projects/project/tsconfig.json": "{}",
		},
	}
	test.Start(t)
	test.End()
}
