// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuild_projectsBuilding_when_there_are_23_projects_in_a_solution(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "projectsBuilding",
		SubScenario:     "when there are 23 projects in a solution",
		CommandLineArgs: []string{"-b", "-v"},
		Cwd:             "/user/username/projects/myproject",
		Files: tsctests.FileMap{
			"/user/username/projects/myproject/pkg0/index.ts": "export const pkg0 = 0;",
			"/user/username/projects/myproject/pkg0/tsconfig.json": `{
    "compilerOptions": { "composite": true },

}`,
			"/user/username/projects/myproject/pkg1/index.ts": "export const pkg1 = 1;",
			"/user/username/projects/myproject/pkg1/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg10/index.ts": "export const pkg10 = 10;",
			"/user/username/projects/myproject/pkg10/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg11/index.ts": "export const pkg11 = 11;",
			"/user/username/projects/myproject/pkg11/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg12/index.ts": "export const pkg12 = 12;",
			"/user/username/projects/myproject/pkg12/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg13/index.ts": "export const pkg13 = 13;",
			"/user/username/projects/myproject/pkg13/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg14/index.ts": "export const pkg14 = 14;",
			"/user/username/projects/myproject/pkg14/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg15/index.ts": "export const pkg15 = 15;",
			"/user/username/projects/myproject/pkg15/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg16/index.ts": "export const pkg16 = 16;",
			"/user/username/projects/myproject/pkg16/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg17/index.ts": "export const pkg17 = 17;",
			"/user/username/projects/myproject/pkg17/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg18/index.ts": "export const pkg18 = 18;",
			"/user/username/projects/myproject/pkg18/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg19/index.ts": "export const pkg19 = 19;",
			"/user/username/projects/myproject/pkg19/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg2/index.ts": "export const pkg2 = 2;",
			"/user/username/projects/myproject/pkg2/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg20/index.ts": "export const pkg20 = 20;",
			"/user/username/projects/myproject/pkg20/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg21/index.ts": "export const pkg21 = 21;",
			"/user/username/projects/myproject/pkg21/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg22/index.ts": "export const pkg22 = 22;",
			"/user/username/projects/myproject/pkg22/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg3/index.ts": "export const pkg3 = 3;",
			"/user/username/projects/myproject/pkg3/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg4/index.ts": "export const pkg4 = 4;",
			"/user/username/projects/myproject/pkg4/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg5/index.ts": "export const pkg5 = 5;",
			"/user/username/projects/myproject/pkg5/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg6/index.ts": "export const pkg6 = 6;",
			"/user/username/projects/myproject/pkg6/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg7/index.ts": "export const pkg7 = 7;",
			"/user/username/projects/myproject/pkg7/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg8/index.ts": "export const pkg8 = 8;",
			"/user/username/projects/myproject/pkg8/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/pkg9/index.ts": "export const pkg9 = 9;",
			"/user/username/projects/myproject/pkg9/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../pkg0" }],
}`,
			"/user/username/projects/myproject/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [
        { "path": "./pkg0" },
        { "path": "./pkg1" },
        { "path": "./pkg2" },
        { "path": "./pkg3" },
        { "path": "./pkg4" },
        { "path": "./pkg5" },
        { "path": "./pkg6" },
        { "path": "./pkg7" },
        { "path": "./pkg8" },
        { "path": "./pkg9" },
        { "path": "./pkg10" },
        { "path": "./pkg11" },
        { "path": "./pkg12" },
        { "path": "./pkg13" },
        { "path": "./pkg14" },
        { "path": "./pkg15" },
        { "path": "./pkg16" },
        { "path": "./pkg17" },
        { "path": "./pkg18" },
        { "path": "./pkg19" },
        { "path": "./pkg20" },
        { "path": "./pkg21" },
        { "path": "./pkg22" }
    ]
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "dts doesn't change",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/myproject/pkg0/index.ts", "export const pkg0 = 0;const someConst2 = 10;")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "dts change",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/myproject/pkg0/index.ts", "export const pkg0 = 0;const someConst2 = 10;export const someConst = 10;")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})
	test.End()
}
