// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_commandLine_Config_with_references_and_empty_file_and_refers_to_config_with_noEmit(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLine",
		SubScenario:     "Config with references and empty file and refers to config with noEmit",
		CommandLineArgs: []string{"-p", "."},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/packages/pkg1/index.ts": "export const a = 1;",
			"/home/src/workspaces/project/packages/pkg1/tsconfig.json": `{
                    "compilerOptions": {
                        "composite": true,
                        "noEmit": true
                    },
                    "files": [
                        "./index.ts",
                    ],
                }`,
			"/home/src/workspaces/project/tsconfig.json": `{
                    "files": [],
                    "references": [
                        {
                            "path": "./packages/pkg1"
                        },
                    ],
                }`,
		},
	}
	test.Start(t)
	test.End()
}
