// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuild_resolveJsonModule_include_and_files(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "resolveJsonModule",
		SubScenario:     "include and files",
		CommandLineArgs: []string{"--b", "project", "--v", "--explainFiles", "--listEmittedFiles"},
		Cwd:             "/home/src/workspaces/solution",
		Files: tsctests.FileMap{
			"/home/src/workspaces/solution/project/src/hello.json": `{
    "hello": "world"
}`,
			"/home/src/workspaces/solution/project/src/index.ts": `import hello from "./hello.json"
export default hello.hello`,
			"/home/src/workspaces/solution/project/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "module": "commonjs",
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "outDir": "dist",
        "skipDefaultLibCheck": true,

    },
    "files": [ "src/hello.json" ], "include": [ "src/**/*" ],
}`,
		},
	}
	test.Start(t)
	test.End()
}
