// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_composite_when_setting_composite_false_on_command_line_but_has_tsbuild_info_in_config(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "composite",
		SubScenario:     "when setting composite false on command line but has tsbuild info in config",
		CommandLineArgs: []string{"--composite", "false"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/src/main.ts": "export const x = 10;",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "composite": true,
        "tsBuildInfoFile": "tsconfig.json.tsbuildinfo",
    },
    "include": [
        "src/**/*.ts",
    ],
}`,
		},
	}
	test.Start(t)
	test.End()
}
