// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_incremental_change_to_type_that_gets_used_as_global_through_export_in_another_file_through_indirect_import(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:    "incremental",
		SubScenario: "change to type that gets used as global through export in another file through indirect import",
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/class1.ts": `const a: MagicNumber = 1;
console.log(a);`,
			"/home/src/workspaces/project/constants.ts": "export default 1;",
			"/home/src/workspaces/project/reexport.ts":  "export { default as ConstantNumber } from \"./constants\"",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "composite": true
    }
}`,
			"/home/src/workspaces/project/types.d.ts": "type MagicNumber = typeof import('./reexport').ConstantNumber",
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "Modify imports used in global file",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/constants.ts", "export default 2;")
		},
	})
	test.End()
}
