// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuild_roots_when_consecutive_and_non_consecutive_are_mixed(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "roots",
		SubScenario:     "when consecutive and non consecutive are mixed",
		CommandLineArgs: []string{"--b", "-v"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/anotherNonConsecutive.ts": `import { random } from "./random2";
export const nonConsecutive = "hello";`,
			"/home/src/workspaces/project/asArray1.ts": `import { random } from "./random1";
export const x = "hello";`,
			"/home/src/workspaces/project/asArray2.ts": "export const x = \"hello\";",
			"/home/src/workspaces/project/asArray3.ts": "export const x = \"hello\";",
			"/home/src/workspaces/project/file1.ts":    "export const x = \"hello\";",
			"/home/src/workspaces/project/file2.ts":    "export const y = \"world\";",
			"/home/src/workspaces/project/nonconsecutive.ts": `import { random } from "./random";
    export const nonConsecutive = "hello";`,
			"/home/src/workspaces/project/random.d.ts":  "export const random = \"hello\";",
			"/home/src/workspaces/project/random1.d.ts": "export const random = \"hello\";",
			"/home/src/workspaces/project/random2.d.ts": "export const random = \"hello\";",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "include": ["file*.ts", "nonconsecutive*.ts", "asArray*.ts", "anotherNonConsecutive.ts"],
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "delete file1",
		Edit: func(sys *tsctests.TestSys) {
			sys.Remove("/home/src/workspaces/project/file1.d.ts")
			sys.Remove("/home/src/workspaces/project/file1.js")
			sys.Remove("/home/src/workspaces/project/file1.ts")
		},
	})
	test.End()
}
