// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuild_moduleResolution_impliedNodeFormat_differs_between_projects_for_shared_file(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "moduleResolution",
		SubScenario:     "impliedNodeFormat differs between projects for shared file",
		CommandLineArgs: []string{"-b", "a", "b", "--verbose", "--traceResolution", "--explainFiles"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/a/src/index.ts": "",
			"/home/src/workspaces/project/a/tsconfig.json": `{
    "compilerOptions": {
        "strict": true
    }
}`,
			"/home/src/workspaces/project/b/package.json": `{
    "name": "b",
    "type": "module"
}`,
			"/home/src/workspaces/project/b/src/index.ts": `import pg from "pg";
pg.foo();`,
			"/home/src/workspaces/project/b/tsconfig.json": `{
    "compilerOptions": { 
        "strict": true,
        "module": "node16"
    },
}`,
			"/home/src/workspaces/project/node_modules/@types/pg/index.d.ts": "export function foo(): void;",
			"/home/src/workspaces/project/node_modules/@types/pg/package.json": `{
    "name": "@types/pg",
    "types": "index.d.ts"
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})
	test.End()
}
