// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tscWatch_commandLineWatch_watch_with_tsconfig_and_incremental(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLineWatch",
		SubScenario:     "watch with tsconfig and incremental",
		CommandLineArgs: []string{"--watch", "--incremental"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/index.ts":      "",
			"/home/src/workspaces/project/tsconfig.json": "{}",
		},
	}
	test.Start(t)
	test.End()
}
