// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_showConfig_Show_TSConfig_with_list_compiler_options_with_enum_value(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "showConfig",
		SubScenario:     "Show TSConfig with list compiler options with enum value",
		CommandLineArgs: []string{"--showConfig", "--lib", "es5,es2015.core"},
	}
	test.Start(t)
	test.End()
}
