// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuild_sample_when_target_option_changes(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "sample",
		SubScenario:     "when target option changes",
		CommandLineArgs: []string{"--b", "core", "--verbose"},
		Cwd:             "/user/username/projects/sample1",
		Files: tsctests.FileMap{
			"/home/src/tslibs/TS/Lib/lib.d.ts": `/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />`,
			"/home/src/tslibs/TS/Lib/lib.esnext.full.d.ts": `/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />`,
			"/user/username/projects/sample1/core/anotherModule.ts": "export const World = \"hello\";",
			"/user/username/projects/sample1/core/index.ts": `export const someString: string = "HELLO WORLD";
export function leftPad(s: string, n: number) { return s + n; }
export function multiply(a: number, b: number) { return a * b; }`,
			"/user/username/projects/sample1/core/some_decl.d.ts": "declare const dts: any;",
			"/user/username/projects/sample1/core/tsconfig.json": `{
    "compilerOptions": {
        "incremental": true,
        "listFiles": true,
        "listEmittedFiles": true,
        "target": "esnext",
    },
}`,
			"/user/username/projects/sample1/logic/index.ts": `import * as c from '../core/index';
export function getSecondsInDay() {
    return c.multiply(10, 15);
}
import * as mod from '../core/anotherModule';
export const m = mod;`,
			"/user/username/projects/sample1/logic/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "declaration": true,
        "sourceMap": true,
        "skipDefaultLibCheck": true,
    },
    "references": [
        { "path": "../core" },
    ],
}`,
			"/user/username/projects/sample1/tests/index.ts": `import * as c from '../core/index';
import * as logic from '../logic/index';

c.leftPad("", 10);
logic.getSecondsInDay();

import * as mod from '../core/anotherModule';
export const m = mod;`,
			"/user/username/projects/sample1/tests/tsconfig.json": `{
    "references": [
        { "path": "../core" },
        { "path": "../logic" },
    ],
    "files": ["index.ts"],
    "compilerOptions": {
        "composite": true,
        "declaration": true,
        "skipDefaultLibCheck": true,
    },
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "incremental-declaration-changes",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/sample1/core/tsconfig.json", `{
    "compilerOptions": {
        "incremental": true,
        "listFiles": true,
        "listEmittedFiles": true,
        "target": "es5",
    },
}`)
		},
	})
	test.End()
}
