// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_commandLine_adds_color_when_FORCE_COLOR_is_set(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:    "commandLine",
		SubScenario: "adds color when FORCE_COLOR is set",
		Env: map[string]string{
			"FORCE_COLOR": "true",
		},
	}
	test.Start(t)
	test.End()
}
