// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_projectReferences_errors_when_the_referenced_project_doesnt_exist(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "projectReferences",
		SubScenario:     "errors when the referenced project doesnt exist",
		CommandLineArgs: []string{"--p", "primary/tsconfig.json"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/primary/a.ts": "export { };",
			"/home/src/workspaces/project/primary/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "outDir": "bin",
    },
    "references": [{
        "path": "../foo"
    }]
}`,
		},
	}
	test.Start(t)
	test.End()
}
