// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_incremental_tsbuildinfo_has_error(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "incremental",
		SubScenario:     "tsbuildinfo has error",
		CommandLineArgs: []string{"-i"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/main.ts":              "export const x = 10;",
			"/home/src/workspaces/project/tsconfig.json":        "{}",
			"/home/src/workspaces/project/tsconfig.tsbuildinfo": "Some random string",
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "tsbuildinfo written has error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/tsconfig.tsbuildinfo", "Some random string{\"version\":\"FakeTSVersion\",\"root\":[2],\"fileNames\":[\"lib.es2025.full.d.ts\",\"./main.ts\"],\"fileInfos\":[{\"version\":\"8859c12c614ce56ba9a18e58384a198f-/// <reference no-default-lib=\\\"true\\\"/>\\ninterface Boolean {}\\ninterface Function {}\\ninterface CallableFunction {}\\ninterface NewableFunction {}\\ninterface IArguments {}\\ninterface Number { toExponential: any; }\\ninterface Object {}\\ninterface RegExp {}\\ninterface String { charAt: any; }\\ninterface Array<T> { length: number; [n: number]: T; }\\ninterface ReadonlyArray<T> {}\\ninterface SymbolConstructor {\\n    (desc?: string | number): symbol;\\n    for(name: string): symbol;\\n    readonly toStringTag: symbol;\\n}\\ndeclare var Symbol: SymbolConstructor;\\ninterface Symbol {\\n    readonly [Symbol.toStringTag]: string;\\n}\\ndeclare const console: { log(msg: any): void; };\",\"affectsGlobalScope\":true,\"impliedNodeFormat\":1},\"28e8748a7acd58f4f59388926e914f86-export const x = 10;\"]}")
		},
	})
	test.End()
}
