// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_incremental_js_file_with_import_in_jsdoc_in_composite_project(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "incremental",
		SubScenario:     "js file with import in jsdoc in composite project",
		CommandLineArgs: []string{"--noEmit"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/index.js": `test("", async function () {
  ;(/** @type {typeof import("a")} */ ({}))
})

test("", async function () {
  ;(/** @type {typeof import("a")} */ a)
})

test("", async function () {
  (/** @type {typeof import("a")} */ ({}))
  ;(/** @type {typeof import("a")} */ ({}))
})

test("", async function () {
  (/** @type {typeof import("a")} */ a)
  ;(/** @type {typeof import("a")} */ a)
})

test("", async function () {
  (/** @type {typeof import("a")} */ ({}))
  ;(/** @type {typeof import("a")} */ ({}))
})`,
			"/home/src/workspaces/project/tsconfig.json": "{\"compilerOptions\": {\"allowJs\": true, \"composite\": true}}",
		},
	}
	test.Start(t)
	test.End()
}
