// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsc_forceConsistentCasingInFileNames_with_relative_and_non_relative_file_resolutions(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "forceConsistentCasingInFileNames",
		SubScenario:     "with relative and non relative file resolutions",
		CommandLineArgs: []string{"/user/username/projects/myproject/src/struct.d.ts", "--forceConsistentCasingInFileNames", "--explainFiles"},
		Cwd:             "/user/username/projects/myproject",
		IgnoreCase:      true,
		Files: tsctests.FileMap{
			"/user/username/projects/myproject/node_modules/fp-ts/lib/struct.d.ts": "export function foo(): void",
			"/user/username/projects/myproject/src/struct.d.ts": `import * as xs1 from "fp-ts/lib/Struct";
import * as xs2 from "fp-ts/lib/struct";
import * as xs3 from "./Struct";
import * as xs4 from "./struct";`,
		},
	}
	test.Start(t)
	test.End()
}
