// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func Test_tsbuild_libraryResolution_with_config(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "libraryResolution",
		SubScenario:     "with config",
		CommandLineArgs: []string{"-b", "project1", "project2", "project3", "project4", "--verbose", "--explainFiles"},
		Cwd:             "/home/src/workspace/projects",
		Files: tsctests.FileMap{
			"/home/src/tslibs/TS/Lib/lib.dom.d.ts":                                       "interface DOMInterface { }",
			"/home/src/tslibs/TS/Lib/lib.scripthost.d.ts":                                "interface ScriptHostInterface { }",
			"/home/src/tslibs/TS/Lib/lib.webworker.d.ts":                                 "interface WebWorkerInterface { }",
			"/home/src/workspace/projects/node_modules/@typescript/unlreated/index.d.ts": "export const unrelated = 10;",
			"/home/src/workspace/projects/project1/core.d.ts":                            "export const core = 10;",
			"/home/src/workspace/projects/project1/file.ts":                              "export const file = 10;",
			"/home/src/workspace/projects/project1/file2.ts": `/// <reference lib="webworker"/>
/// <reference lib="scripthost"/>
/// <reference lib="es5"/>`,
			"/home/src/workspace/projects/project1/index.ts": "export const x = \"type1\";",
			"/home/src/workspace/projects/project1/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "typeRoots": ["./typeroot1"],
        "lib": ["es5", "dom"],
        "traceResolution": true,
        "libReplacement": false
    }
}`,
			"/home/src/workspace/projects/project1/typeroot1/sometype/index.d.ts": "export type TheNum = \"type1\";",
			"/home/src/workspace/projects/project1/utils.d.ts":                    "export const y = 10;",
			"/home/src/workspace/projects/project2/index.ts":                      "export const y = 10",
			"/home/src/workspace/projects/project2/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "lib": ["es5", "dom"],
        "traceResolution": true,
        "libReplacement": false
    }
}`,
			"/home/src/workspace/projects/project2/utils.d.ts": "export const y = 10;",
			"/home/src/workspace/projects/project3/index.ts":   "export const z = 10",
			"/home/src/workspace/projects/project3/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "lib": ["es5", "dom"],
        "traceResolution": true,
        "libReplacement": false
    }
}`,
			"/home/src/workspace/projects/project3/utils.d.ts": "export const y = 10;",
			"/home/src/workspace/projects/project4/index.ts":   "export const z = 10",
			"/home/src/workspace/projects/project4/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "lib": ["esnext", "dom", "webworker"],
        "traceResolution": true,
        "libReplacement": false
    }
}`,
			"/home/src/workspace/projects/project4/utils.d.ts": "export const y = 10;",
		},
	}
	test.Start(t)
	test.End()
}
