// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_lateBoundSymbol_interface_is_merged_and_contains_late_bound_member(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "lateBoundSymbol",
		SubScenario:     "interface is merged and contains late bound member",
		CommandLineArgs: []string{"--b", "--verbose"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/src/globals.d.ts": `interface SymbolConstructor {
    (description?: string | number): symbol;
}
declare var Symbol: SymbolConstructor;`,
			"/home/src/workspaces/project/src/hkt.ts": "export interface HKT<T> { }",
			"/home/src/workspaces/project/src/main.ts": `import { HKT } from "./hkt";

const sym = Symbol();

declare module "./hkt" {
    interface HKT<T> {
        [sym]: { a: T }
    }
}
const x = 10;
type A = HKT<number>[typeof sym];`,
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "rootDir": "src",
        "incremental": true,
    },
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "incremental-declaration-doesnt-change",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/main.ts", `import { HKT } from "./hkt";

const sym = Symbol();

declare module "./hkt" {
    interface HKT<T> {
        [sym]: { a: T }
    }
}

type A = HKT<number>[typeof sym];`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "incremental-declaration-doesnt-change",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/main.ts", `import { HKT } from "./hkt";

const sym = Symbol();

declare module "./hkt" {
    interface HKT<T> {
        [sym]: { a: T }
    }
}

type A = HKT<number>[typeof sym];const x = 10;`)
		},
	})
	test.End()
}
