// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_noCheck_dts_errors(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "noCheck",
		SubScenario:     "dts errors",
		CommandLineArgs: []string{"-b", "-v", "--noCheck"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/a.ts": "export const a = class { private p = 10; };",
			"/home/src/workspaces/project/b.ts": "export const b = 10;",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "declaration": true,
        "incremental": false
    }
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Fix `a` error with noCheck",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/a.ts", "export const a = \"hello\";")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with checking",
		CommandLineArgs: []string{"-b", "-v"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with checking",
		CommandLineArgs: []string{"-b", "-v"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Introduce error with noCheck",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/a.ts", "export const a = class { private p = 10; };")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with checking",
		CommandLineArgs: []string{"-b", "-v"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Fix `a` error with noCheck",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/a.ts", "export const a = \"hello\";")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with checking",
		CommandLineArgs: []string{"-b", "-v"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "Add file with error",
		CommandLineArgs: []string{"-b", "-v"},
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/c.ts", "export const c: number = \"hello\";")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Introduce error with noCheck",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/a.ts", "export const a = class { private p = 10; };")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Fix `a` error with noCheck",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/a.ts", "export const a = \"hello\";")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with checking",
		CommandLineArgs: []string{"-b", "-v"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with checking",
		CommandLineArgs: []string{"-b", "-v"},
	})
	test.End()
}
