// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_declarationEmit_reports_dts_generation_errors(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "declarationEmit",
		SubScenario:     "reports dts generation errors",
		CommandLineArgs: []string{"-b", "--explainFiles", "--listEmittedFiles", "--v"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/index.ts": `import ky from 'ky';
export const api = ky.extend({});`,
			"/home/src/workspaces/project/node_modules/ky/distribution/index.d.ts": `type KyInstance = {
    extend(options: Record<string,unknown>): KyInstance;
}
declare const ky: KyInstance;
export default ky;`,
			"/home/src/workspaces/project/node_modules/ky/package.json": `{
    "name": "ky",
    "type": "module",
    "main": "./distribution/index.js"
}`,
			"/home/src/workspaces/project/package.json": `{
    "type": "module"
}`,
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "module": "NodeNext",
        "moduleResolution": "NodeNext",
        "composite": false,
        "incremental": false,
        "declaration": true,
        "skipLibCheck": true,
        "skipDefaultLibCheck": true,
    },
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})
	test.End()
}
