// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_commandLine_bad_locale(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLine",
		SubScenario:     "bad locale",
		CommandLineArgs: []string{"--build", "--help", "--locale", "whoops"},
	}
	test.Start(t)
	test.End()
}
