// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_fileDelete_detects_deleted_file(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "fileDelete",
		SubScenario:     "detects deleted file",
		CommandLineArgs: []string{"--b", "main/tsconfig.json", "-v", "--traceResolution", "--explainFiles"},
		Cwd:             "/home/src/workspaces/solution",
		Files: tsctests.FileMap{
			"/home/src/workspaces/solution/child/child.ts": `import { child2 } from "../child/child2";
export function child() {
    child2();
}`,
			"/home/src/workspaces/solution/child/child2.ts": `export function child2() {
}`,
			"/home/src/workspaces/solution/child/tsconfig.json": `{
    "compilerOptions": { "composite": true }
}`,
			"/home/src/workspaces/solution/main/main.ts": `import { child } from "../child/child";
export function main() {
    child();
}`,
			"/home/src/workspaces/solution/main/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../child" }],
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "delete child2 file",
		Edit: func(sys *tsctests.TestSys) {
			sys.Remove("/home/src/workspaces/solution/child/child2.d.ts")
			sys.Remove("/home/src/workspaces/solution/child/child2.js")
			sys.Remove("/home/src/workspaces/solution/child/child2.ts")
		},
	})
	test.End()
}
