// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_clean_file_name_and_output_name_clashing(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "clean",
		SubScenario:     "file name and output name clashing",
		CommandLineArgs: []string{"--b", "--clean"},
		Cwd:             "/home/src/workspaces/solution",
		Files: tsctests.FileMap{
			"/home/src/workspaces/solution/bar.ts":   "",
			"/home/src/workspaces/solution/index.js": "",
			"/home/src/workspaces/solution/tsconfig.json": `{
    "compilerOptions": { "allowJs": true }
}`,
		},
	}
	test.Start(t)
	test.End()
}
