// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_resolveJsonModule_importing_json_module_from_project_reference(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "resolveJsonModule",
		SubScenario:     "importing json module from project reference",
		CommandLineArgs: []string{"--b", "project", "--verbose", "--explainFiles"},
		Cwd:             "/home/src/workspaces/solution",
		Files: tsctests.FileMap{
			"/home/src/workspaces/solution/project/main/index.ts": `import { foo } from '../strings/foo.json';
console.log(foo);`,
			"/home/src/workspaces/solution/project/main/tsconfig.json": `{
    "extends": "../tsconfig.json",
    "include": [
        "./**/*.ts",
    ],
    "references": [{
        "path": "../strings/tsconfig.json",
    }],
}`,
			"/home/src/workspaces/solution/project/strings/foo.json": `{
    "foo": "bar baz"
}`,
			"/home/src/workspaces/solution/project/strings/tsconfig.json": `{
    "extends": "../tsconfig.json",
    "include": ["foo.json"],
    "references": [],
}`,
			"/home/src/workspaces/solution/project/tsconfig.json": `{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "rootDir": "./",
        "composite": true,
        "resolveJsonModule": true,
        "strict": true,
        "esModuleInterop": true,
    },
    "references": [
        { "path": "./strings/tsconfig.json" },
        { "path": "./main/tsconfig.json" },
    ],
    "files": [],
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})
	test.End()
}
