// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_javascriptProjectEmit_loads_js_based_projects_and_emits_them_correctly(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "javascriptProjectEmit",
		SubScenario:     "loads js-based projects and emits them correctly",
		CommandLineArgs: []string{"--b"},
		Cwd:             "/home/src/workspaces/solution",
		Files: tsctests.FileMap{
			"/home/src/tslibs/TS/Lib/lib.d.ts": `/// <reference no-default-lib="true"/>
interface Boolean {}
interface Function {}
interface CallableFunction {}
interface NewableFunction {}
interface IArguments {}
interface Number { toExponential: any; }
interface Object {}
interface RegExp {}
interface String { charAt: any; }
interface Array<T> { length: number; [n: number]: T; }
interface ReadonlyArray<T> {}
interface SymbolConstructor {
    readonly species: symbol;
    (desc?: string | number): symbol;
    for(name: string): symbol;
    readonly toStringTag: symbol;
}
declare var Symbol: SymbolConstructor;
interface Symbol {
    readonly [Symbol.toStringTag]: string;
}
declare const console: { log(msg: any): void; };`,
			"/home/src/workspaces/solution/common/nominal.js": `/**
 * @template T, Name
 * @typedef {T & {[Symbol.species]: Name}} Nominal
 */
module.exports = {};`,
			"/home/src/workspaces/solution/common/tsconfig.json": `{
    "extends": "../tsconfig.base.json",
    "compilerOptions": {
        "composite": true,
    },
    "include": ["nominal.js"],
}`,
			"/home/src/workspaces/solution/sub-project-2/index.js": `import { MyNominal } from '../sub-project/index';

const variable = {
    key: /** @type {MyNominal} */('value'),
};

/**
 * @return {keyof typeof variable}
 */
export function getVar() {
    return 'key';
}`,
			"/home/src/workspaces/solution/sub-project-2/tsconfig.json": `{
    "extends": "../tsconfig.base.json",
    "compilerOptions": {
        "composite": true,
    },
    "references": [
        { "path": "../sub-project" },
    ],
    "include": ["./index.js"],
}`,
			"/home/src/workspaces/solution/sub-project/index.js": `import { Nominal } from '../common/nominal';

/**
 * @typedef {Nominal<string, 'MyNominal'>} MyNominal
 */`,
			"/home/src/workspaces/solution/sub-project/tsconfig.json": `{
    "extends": "../tsconfig.base.json",
    "compilerOptions": {
        "composite": true,
    },
    "references": [
        { "path": "../common" },
    ],
    "include": ["./index.js"],
}`,
			"/home/src/workspaces/solution/tsconfig.base.json": `{
    "compilerOptions": {
        "skipLibCheck": true,
        "rootDir": "./",
        "outDir": "../lib",
        "allowJs": true,
        "checkJs": true,
        "declaration": true,
    },
}`,
			"/home/src/workspaces/solution/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
    },
    "references": [
        { "path": "./sub-project" },
        { "path": "./sub-project-2" },
    ],
    "include": [],
}`,
		},
	}
	test.Start(t)
	test.End()
}
