// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_declarationEmit_when_declaration_file_used_inferred_type_from_referenced_project(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "declarationEmit",
		SubScenario:     "when declaration file used inferred type from referenced project",
		CommandLineArgs: []string{"--b", "packages/pkg2/tsconfig.json", "--verbose"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/packages/pkg1/src/index.ts": `export interface IThing {
    a: string;
}
export interface IThings {
    thing1: IThing;
}`,
			"/home/src/workspaces/project/packages/pkg1/tsconfig.json": `{
    "extends": "../../tsconfig",
    "compilerOptions": { "outDir": "lib" },
    "include": ["src"],
}`,
			"/home/src/workspaces/project/packages/pkg2/src/index.ts": `import { IThings } from '@fluentui/pkg1';
export function fn4() {
    const a: IThings = { thing1: { a: 'b' } };
    return a.thing1;
}`,
			"/home/src/workspaces/project/packages/pkg2/tsconfig.json": `{
    "extends": "../../tsconfig",
    "compilerOptions": { "outDir": "lib" },
    "include": ["src"],
    "references": [{ "path": "../pkg1" }],
}`,
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "paths": { "@fluentui/*": ["./packages/*/src"] },
    },
}`,
		},
	}
	test.Start(t)
	test.End()
}
