// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuildWatch_noEmit_dts_errors_with_incremental_as_modules(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "noEmit",
		SubScenario:     "dts errors with incremental as modules",
		CommandLineArgs: []string{"-b", "-verbose", "-w"},
		Cwd:             "/home/src/projects/project",
		Files: tsctests.FileMap{
			"/home/src/projects/project/a.ts": "export const a = class { private p = 10; };",
			"/home/src/projects/project/b.ts": "export const b = 10;",
			"/home/src/projects/project/tsconfig.json": `{
    "compilerOptions": {
        "incremental": true,
        "declaration": true
    , "noEmit": true }
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "Fix error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/projects/project/a.ts", "export const a = \"hello\";")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Emit after fixing error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/projects/project/tsconfig.json", `{
    "compilerOptions": {
        "incremental": true,
        "declaration": true
    , "noEmit": false }
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no Emit run after fixing error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/projects/project/tsconfig.json", `{
    "compilerOptions": {
        "incremental": true,
        "declaration": true
    , "noEmit": true }
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Introduce error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/projects/project/a.ts", "const a = class { private p = 10; };")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Emit when error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/projects/project/tsconfig.json", `{
    "compilerOptions": {
        "incremental": true,
        "declaration": true
    , "noEmit": false }
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no Emit run when error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/projects/project/tsconfig.json", `{
    "compilerOptions": {
        "incremental": true,
        "declaration": true
    , "noEmit": true }
}`)
		},
	})
	test.End()
}
