// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_inferredTypeFromTransitiveModule_inferred_type_from_transitive_module(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "inferredTypeFromTransitiveModule",
		SubScenario:     "inferred type from transitive module",
		CommandLineArgs: []string{"--b", "--verbose"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/bar.ts": `interface RawAction {
    (...args: any[]): Promise<any> | void;
}
interface ActionFactory {
    <T extends RawAction>(target: T): T;
}
declare function foo<U extends any[] = any[]>(): ActionFactory;
export default foo()(function foobar(param: string): void {
});`,
			"/home/src/workspaces/project/bundling.ts": `export class LazyModule<TModule> {
    constructor(private importCallback: () => Promise<TModule>) {}
}

export class LazyAction<
    TAction extends (...args: any[]) => any,
    TModule
>  {
    constructor(_lazyModule: LazyModule<TModule>, _getter: (module: TModule) => TAction) {
    }
}`,
			"/home/src/workspaces/project/global.d.ts": `interface PromiseConstructor {
    new <T>(): Promise<T>;
}
declare var Promise: PromiseConstructor;
interface Promise<T> {
}`,
			"/home/src/workspaces/project/index.ts": `import { LazyAction, LazyModule } from './bundling';
const lazyModule = new LazyModule(() =>
    import('./lazyIndex')
);
export const lazyBar = new LazyAction(lazyModule, m => m.bar);`,
			"/home/src/workspaces/project/lazyIndex.ts": "export { default as bar } from './bar';",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "target": "es5",
        "declaration": true,
        "outDir": "obj",
        "incremental": true,
        "isolatedModules": false,
    },
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "incremental-declaration-changes",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/bar.ts", `interface RawAction {
    (...args: any[]): Promise<any> | void;
}
interface ActionFactory {
    <T extends RawAction>(target: T): T;
}
declare function foo<U extends any[] = any[]>(): ActionFactory;
export default foo()(function foobar(): void {
});`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "incremental-declaration-changes",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/bar.ts", `interface RawAction {
    (...args: any[]): Promise<any> | void;
}
interface ActionFactory {
    <T extends RawAction>(target: T): T;
}
declare function foo<U extends any[] = any[]>(): ActionFactory;
export default foo()(function foobar(param: string): void {
});`)
		},
	})
	test.End()
}
