// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_emitDeclarationOnly_only_dts_output_in_circular_import_project_with_emitDeclarationOnly(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "emitDeclarationOnly",
		SubScenario:     "only dts output in circular import project with emitDeclarationOnly",
		CommandLineArgs: []string{"--b", "--verbose"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/src/a.ts": `import { B } from "./b";

export interface A {
    b: B;
}`,
			"/home/src/workspaces/project/src/b.ts": `import { C } from "./c";

export interface B {
    b: C;
}`,
			"/home/src/workspaces/project/src/c.ts": `import { A } from "./a";

export interface C {
    a: A;
}`,
			"/home/src/workspaces/project/src/index.ts": `export { A } from "./a";
export { B } from "./b";
export { C } from "./c";`,
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "incremental": true,
        "target": "es5",
        "module": "commonjs",
        "declaration": true,
        "declarationMap": false,
        "sourceMap": true,
        "outDir": "./lib",
        "composite": true,
        "strict": true,
        "esModuleInterop": true,
        "alwaysStrict": true,
        "rootDir": "src",
        "emitDeclarationOnly": true,
    },
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "incremental-declaration-changes",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/a.ts", `import { B } from "./b";

export interface A {
    b: B; foo: any;
}`)
		},
	})
	test.End()
}
