// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_transitiveReferences_reports_error_about_module_not_found_with_node_resolution_with_external_module_name(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "transitiveReferences",
		SubScenario:     "reports error about module not found with node resolution with external module name",
		CommandLineArgs: []string{"--b", "tsconfig.c.json", "--listFiles"},
		Cwd:             "/user/username/projects/transitiveReferences",
		Files: tsctests.FileMap{
			"/user/username/projects/transitiveReferences/a.ts": "export class A {}",
			"/user/username/projects/transitiveReferences/b.ts": `import {A} from 'a';
export const b = new A();`,
			"/user/username/projects/transitiveReferences/c.ts": `import {b} from './b';
import {X} from "@ref/a";
b;
X;`,
			"/user/username/projects/transitiveReferences/refs/a.d.ts": `export class X {}
export class A {}`,
			"/user/username/projects/transitiveReferences/tsconfig.a.json": `{
    "files": ["a.ts"],
    "compilerOptions": {
        "composite": true,
    },
}`,
			"/user/username/projects/transitiveReferences/tsconfig.b.json": `{
    "files": ["b.ts"],
    "compilerOptions": {
        "composite": true,
        "module": "nodenext",
    },
    "references": [{ "path": "tsconfig.a.json" }],
}`,
			"/user/username/projects/transitiveReferences/tsconfig.c.json": `{
    "files": ["c.ts"],
    "compilerOptions": {
        "paths": {
            "@ref/*": ["./refs/*"],
        },
    },
    "references": [{ "path": "tsconfig.b.json" }],
}`,
		},
	}
	test.Start(t)
	test.End()
}
