// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_noEmitOnError_syntax_errors(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "noEmitOnError",
		SubScenario:     "syntax errors",
		CommandLineArgs: []string{"-b", "-v"},
		Cwd:             "/user/username/projects/noEmitOnError",
		Files: tsctests.FileMap{
			"/user/username/projects/noEmitOnError/shared/types/db.ts": `export interface A {
    name: string;
}`,
			"/user/username/projects/noEmitOnError/src/main.ts": `import { A } from "../shared/types/db";
const a = {
    lastName: 'sdsd'
;`,
			"/user/username/projects/noEmitOnError/src/other.ts": `console.log("hi");
export { }`,
			"/user/username/projects/noEmitOnError/tsconfig.json": `{
    "compilerOptions": {
        "outDir": "./dev-build",
        "declaration": false,
        "incremental": false,
        "noEmitOnError": true,
    },
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Fix error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/user/username/projects/noEmitOnError/src/main.ts", `import { A } from "../shared/types/db";
const a = {
    lastName: 'sdsd'
};`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})
	test.End()
}
