// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_fileDelete_deleted_file_without_composite(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "fileDelete",
		SubScenario:     "deleted file without composite",
		CommandLineArgs: []string{"--b", "child/tsconfig.json", "-v", "--traceResolution", "--explainFiles"},
		Cwd:             "/home/src/workspaces/solution",
		Files: tsctests.FileMap{
			"/home/src/workspaces/solution/child/child.ts": `import { child2 } from "../child/child2";
export function child() {
    child2();
}`,
			"/home/src/workspaces/solution/child/child2.ts": `export function child2() {
}`,
			"/home/src/workspaces/solution/child/tsconfig.json": `{
    "compilerOptions": { }
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "delete child2 file",
		Edit: func(sys *tsctests.TestSys) {
			sys.Remove("/home/src/workspaces/solution/child/child2.js")
			sys.Remove("/home/src/workspaces/solution/child/child2.ts")
		},
	})
	test.End()
}
