// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_configFileErrors_reports_syntax_errors_in_config_file(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "configFileErrors",
		SubScenario:     "reports syntax errors in config file",
		CommandLineArgs: []string{"--b"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/a.ts": "export function foo() { }",
			"/home/src/workspaces/project/b.ts": "export function bar() { }",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
    },
    "files": [
        "a.ts"
        "b.ts"
    ]
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "reports syntax errors after change to config file",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/tsconfig.json", `{
    "compilerOptions": {
        "composite": true, "declaration": true
    },
    "files": [
        "a.ts"
        "b.ts"
    ]
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "reports syntax errors after change to ts file",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/a.ts", "export function foo() { }export function fooBar() { }")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "builds after fixing config file errors",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/tsconfig.json", `{
    "compilerOptions": {
        "composite": true, "declaration": true
    },
    "files": [
        "a.ts",
        "b.ts"
    ]
}`)
		},
	})
	test.End()
}
