// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_solution_does_not_have_empty_files_diagnostic_when_files_is_empty_and_references_are_provided(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "solution",
		SubScenario:     "does not have empty files diagnostic when files is empty and references are provided",
		CommandLineArgs: []string{"--b", "with-references"},
		Cwd:             "/home/src/workspaces/solution",
		Files: tsctests.FileMap{
			"/home/src/workspaces/solution/core/index.ts": "export function multiply(a: number, b: number) { return a * b; }",
			"/home/src/workspaces/solution/core/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "declaration": true,
        "declarationMap": true,
        "skipDefaultLibCheck": true,
    },
}`,
			"/home/src/workspaces/solution/with-references/tsconfig.json": `{
    "references": [
        { "path": "../core" },
    ],
    "files": [],
    "compilerOptions": {
        "composite": true,
        "declaration": true,
        "forceConsistentCasingInFileNames": true,
        "skipDefaultLibCheck": true,
    },
}`,
		},
	}
	test.Start(t)
	test.End()
}
