// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_moduleResolution_type_reference_resolution_uses_correct_options_for_different_resolution_options_referenced_project(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "moduleResolution",
		SubScenario:     "type reference resolution uses correct options for different resolution options referenced project",
		CommandLineArgs: []string{"-b", "packages/pkg1.tsconfig.json", "packages/pkg2.tsconfig.json", "--verbose", "--traceResolution"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/packages/pkg1.tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "typeRoots": ["./typeroot1"]
    },
    "files": ["./pkg1_index.ts"],
}`,
			"/home/src/workspaces/project/packages/pkg1_index.ts": "export const theNum: TheNum = \"type1\";",
			"/home/src/workspaces/project/packages/pkg2.tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "typeRoots": ["./typeroot2"]
    },
    "files": ["./pkg2_index.ts"],
}`,
			"/home/src/workspaces/project/packages/pkg2_index.ts":                 "export const theNum: TheNum2 = \"type2\";",
			"/home/src/workspaces/project/packages/typeroot1/sometype/index.d.ts": "declare type TheNum = \"type1\";",
			"/home/src/workspaces/project/packages/typeroot2/sometype/index.d.ts": "declare type TheNum2 = \"type2\";",
		},
	}
	test.Start(t)
	test.End()
}
