// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsbuild_declarationEmit_when_declaration_file_is_referenced_through_triple_slash(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "declarationEmit",
		SubScenario:     "when declaration file is referenced through triple slash",
		CommandLineArgs: []string{"--b", "--verbose"},
		Cwd:             "/home/src/workspaces/solution",
		Files: tsctests.FileMap{
			"/home/src/workspaces/solution/src/common/nominal.ts": `/// <reference path="./types.d.ts" preserve="true" />
export declare type Nominal<T, Name extends string> = MyNominal<T, Name>;`,
			"/home/src/workspaces/solution/src/common/tsconfig.json": `{
    "extends": "../../tsconfig.base.json",
    "compilerOptions": { "composite": true },
    "include": ["./nominal.ts"],
}`,
			"/home/src/workspaces/solution/src/common/types.d.ts": `declare type MyNominal<T, Name extends string> = T & {
    specialKey: Name;
};`,
			"/home/src/workspaces/solution/src/subProject/index.ts": `import { Nominal } from '../common/nominal';
export type MyNominal = Nominal<string, 'MyNominal'>;`,
			"/home/src/workspaces/solution/src/subProject/tsconfig.json": `{
    "extends": "../../tsconfig.base.json",
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../common" }],
    "include": ["./index.ts"],
}`,
			"/home/src/workspaces/solution/src/subProject2/index.ts": `import { MyNominal } from '../subProject/index';
const variable = {
    key: 'value' as MyNominal,
};
export function getVar(): keyof typeof variable {
    return 'key';
}`,
			"/home/src/workspaces/solution/src/subProject2/tsconfig.json": `{
    "extends": "../../tsconfig.base.json",
    "compilerOptions": { "composite": true },
    "references": [{ "path": "../subProject" }],
    "include": ["./index.ts"],
}`,
			"/home/src/workspaces/solution/src/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "./subProject" }, { "path": "./subProject2" }],
    "include": [],
}`,
			"/home/src/workspaces/solution/tsconfig.base.json": `{
    "compilerOptions": {
        "rootDir": "./",
        "outDir": "lib",
    },
}`,
			"/home/src/workspaces/solution/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "references": [{ "path": "./src" }],
    "include": [],
}`,
		},
	}
	test.Start(t)
	test.End()
}
