// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_projectReferences_issues_a_nice_error_when_the_input_file_is_missing(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "projectReferences",
		SubScenario:     "issues a nice error when the input file is missing",
		CommandLineArgs: []string{"--p", "beta/tsconfig.json"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/alpha/a.ts": "export const m: number = 3;",
			"/home/src/workspaces/project/alpha/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "outDir": "bin",
    },
    "references": []
}`,
			"/home/src/workspaces/project/beta/b.ts": "import { m } from '../alpha/a'",
			"/home/src/workspaces/project/beta/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "outDir": "bin",
    },
    "references": [ { "path": "../alpha" } ]
}`,
		},
	}
	test.Start(t)
	test.End()
}
