// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_incremental_when_file_is_deleted(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:    "incremental",
		SubScenario: "when file is deleted",
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/file1.ts": "export class  C { }",
			"/home/src/workspaces/project/file2.ts": "export class D { }",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "outDir": "outDir"
    }
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "delete file with imports",
		Edit: func(sys *tsctests.TestSys) {
			sys.Remove("/home/src/workspaces/project/file2.ts")
		},
	})
	test.End()
}
