// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_composite_synthetic_jsx_import_of_ESM_module_from_CJS_module_no_crash_no_jsx_element(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:    "composite",
		SubScenario: "synthetic jsx import of ESM module from CJS module no crash no jsx element",
		Cwd:         "/home/src/projects/project",
		Files: tsctests.FileMap{
			"/home/src/projects/project/node_modules/solid-js/jsx-runtime.d.ts": `export namespace JSX {
    type IntrinsicElements = { div: {}; };
}`,
			"/home/src/projects/project/node_modules/solid-js/package.json": `{
    "name": "solid-js",
    "type": "module"
}`,
			"/home/src/projects/project/src/main.ts": "export default 42;",
			"/home/src/projects/project/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "module": "Node16",
        "jsx": "react-jsx",
        "jsxImportSource": "solid-js",
    },
}`,
		},
	}
	test.Start(t)
	test.End()
}
