// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_projectReferences_rewriteRelativeImportExtensionsProjectReferences3(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "projectReferences",
		SubScenario:     "rewriteRelativeImportExtensionsProjectReferences3",
		CommandLineArgs: []string{"--p", "src/services", "--pretty", "false"},
		Cwd:             "/home/src/workspaces/solution",
		Files: tsctests.FileMap{
			"/home/src/workspaces/solution/dist/compiler/parser.d.ts": "export {};",
			"/home/src/workspaces/solution/src/compiler/parser.ts":    "export {};",
			"/home/src/workspaces/solution/src/compiler/tsconfig.json": `{
    "extends": "../tsconfig-base.json",
    "compilerOptions": {
        "rootDir": ".",
        "outDir": "../../dist/compiler"
    }
}`,
			"/home/src/workspaces/solution/src/services/services.ts": "import {} from \"../compiler/parser.ts\";",
			"/home/src/workspaces/solution/src/services/tsconfig.json": `{
    "extends": "../tsconfig-base.json",
    "compilerOptions": {
        "rootDir": ".", 
        "outDir": "../../dist/services"
    },
    "references": [
        { "path": "../compiler" }
    ]
}`,
			"/home/src/workspaces/solution/src/tsconfig-base.json": `{
    "compilerOptions": { 
        "module": "nodenext",
        "composite": true,
        "rewriteRelativeImportExtensions": true
    }
}`,
		},
	}
	test.Start(t)
	test.End()
}
