// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_moduleResolution_package_json_scope(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "moduleResolution",
		SubScenario:     "package json scope",
		CommandLineArgs: []string{"-p", "src", "--explainFiles", "--extendedDiagnostics"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/package.json": `{
    "name": "app",
    "version": "1.0.0"
}`,
			"/home/src/workspaces/project/src/fileA.ts": `import { foo } from "./fileB.mjs";
foo();`,
			"/home/src/workspaces/project/src/fileB.mts": "export function foo() {}",
			"/home/src/workspaces/project/src/main.ts":   "export const x = 10;",
			"/home/src/workspaces/project/src/tsconfig.json": `{
    "compilerOptions": {
        "target": "ES2016",
        "composite": true,
        "module": "Node16",
        "traceResolution": true,
    },
    "files": [
        "main.ts",
        "fileA.ts",
        "fileB.mts",
    ],
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "Delete package.json",
		Edit: func(sys *tsctests.TestSys) {
			sys.Remove("/home/src/workspaces/project/package.json")
		},
	})
	test.End()
}
