// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_incremental_when_global_file_is_added_the_signatures_are_updated(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "incremental",
		SubScenario:     "when global file is added, the signatures are updated",
		CommandLineArgs: []string{},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/src/anotherFileWithSameReferenes.ts": `/// <reference path="./filePresent.ts"/>
/// <reference path="./fileNotFound.ts"/>
function anotherFileWithSameReferenes() { }`,
			"/home/src/workspaces/project/src/filePresent.ts": "function something() { return 10; }",
			"/home/src/workspaces/project/src/main.ts": `/// <reference path="./filePresent.ts"/>
/// <reference path="./fileNotFound.ts"/>
function main() { }`,
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": { "composite": true },
    "include": ["src/**/*.ts"],
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Modify main file",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/main.ts", `/// <reference path="./filePresent.ts"/>
/// <reference path="./fileNotFound.ts"/>
function main() { }something();`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Modify main file again",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/main.ts", `/// <reference path="./filePresent.ts"/>
/// <reference path="./fileNotFound.ts"/>
function main() { }something();something();`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Add new file and update main file",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/main.ts", `/// <reference path="./newFile.ts"/>
/// <reference path="./filePresent.ts"/>
/// <reference path="./fileNotFound.ts"/>
function main() { }something();something();foo();`)
			sys.WriteFile("/home/src/workspaces/project/src/newFile.ts", "function foo() { return 20; }")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Write file that could not be resolved",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/fileNotFound.ts", "function something2() { return 20; }")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Modify main file",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/main.ts", `/// <reference path="./newFile.ts"/>
/// <reference path="./filePresent.ts"/>
/// <reference path="./fileNotFound.ts"/>
function main() { }something();something();foo();something();`)
		},
	})
	test.End()
}
