// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_showConfig_Show_TSConfig_with_incorrect_compiler_option_value(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "showConfig",
		SubScenario:     "Show TSConfig with incorrect compiler option value",
		CommandLineArgs: []string{"--showConfig", "--lib", "nonExistLib,es5,es2015.promise"},
	}
	test.Start(t)
	test.End()
}
