// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_commandLine_Initialized_TSConfig_with_files_options(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLine",
		SubScenario:     "Initialized TSConfig with files options",
		CommandLineArgs: []string{"--init", "file0.st", "file1.ts", "file2.ts"},
	}
	test.Start(t)
	test.End()
}
