// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_showConfig_Show_TSConfig_with_incorrect_compiler_option(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "showConfig",
		SubScenario:     "Show TSConfig with incorrect compiler option",
		CommandLineArgs: []string{"--showConfig", "--someNonExistOption"},
	}
	test.Start(t)
	test.End()
}
