// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
	"github.com/microsoft/typescript-go/internal/vfs/vfstest"
)

func TestTsc_declarationEmit_when_pkg_references_sibling_package_through_indirect_symlink(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "declarationEmit",
		SubScenario:     "when pkg references sibling package through indirect symlink",
		CommandLineArgs: []string{"-p", "pkg3", "--explainFiles"},
		Cwd:             "/user/username/projects/myproject",
		Files: tsctests.FileMap{
			"/user/username/projects/myproject/pkg1/dist/index.d.ts": "export * from './types';",
			"/user/username/projects/myproject/pkg1/dist/types.d.ts": `export declare type A = {
    id: string;
};
export declare type B = {
    id: number;
};
export declare type IdType = A | B;
export declare class MetadataAccessor<T, D extends IdType = IdType> {
    readonly key: string;
    private constructor();
    toString(): string;
    static create<T, D extends IdType = IdType>(key: string): MetadataAccessor<T, D>;
}`,
			"/user/username/projects/myproject/pkg1/package.json": `{
    "name": "@raymondfeng/pkg1",
    "version": "1.0.0",
    "main": "dist/index.js",
    "typings": "dist/index.d.ts"
}`,
			"/user/username/projects/myproject/pkg2/dist/index.d.ts":                "export * from './types';",
			"/user/username/projects/myproject/pkg2/dist/types.d.ts":                "export {MetadataAccessor} from '@raymondfeng/pkg1';",
			"/user/username/projects/myproject/pkg2/node_modules/@raymondfeng/pkg1": vfstest.Symlink("/user/username/projects/myproject/pkg1"),
			"/user/username/projects/myproject/pkg2/package.json": `{
    "name": "@raymondfeng/pkg2",
    "version": "1.0.0",
    "main": "dist/index.js",
    "typings": "dist/index.d.ts"
}`,
			"/user/username/projects/myproject/pkg3/node_modules/@raymondfeng/pkg2": vfstest.Symlink("/user/username/projects/myproject/pkg2"),
			"/user/username/projects/myproject/pkg3/src/index.ts":                   "export * from './keys';",
			"/user/username/projects/myproject/pkg3/src/keys.ts": `import {MetadataAccessor} from "@raymondfeng/pkg2";
export const ADMIN = MetadataAccessor.create<boolean>('1');`,
			"/user/username/projects/myproject/pkg3/tsconfig.json": `{
    "compilerOptions": {
        "outDir": "dist",
        "rootDir": "src",
        "target": "es5",
        "module": "commonjs",
        "strict": true,
        "esModuleInterop": true,
        "declaration": true,
    },
}`,
		},
	}
	test.Start(t)
	test.End()
}
