// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_ignoreConfig_without_any_options_when_config_file_absent(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:    "ignoreConfig",
		SubScenario: "without any options when config file absent",
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/c.ts":     "export const c = 10;",
			"/home/src/workspaces/project/src/a.ts": "export const a = 10;",
			"/home/src/workspaces/project/src/b.ts": "export const b = 10;",
		},
	}
	test.Start(t)
	test.End()
}
