// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_showConfig_Show_TSConfig_with_exclude(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "showConfig",
		SubScenario:     "Show TSConfig with exclude",
		CommandLineArgs: []string{"-p", "tsconfig.json", "--showConfig"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/src/index.ts":  "export const a = 1;",
			"/home/src/workspaces/project/test/test1.ts": "import { a } from \"../src\";",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "strict": true
    },
    "exclude": [
        "test"
    ]
}`,
		},
	}
	test.Start(t)
	test.End()
}
