// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_noEmitOnError_when_declarationMap_changes(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:    "noEmitOnError",
		SubScenario: "when declarationMap changes",
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/a.ts": "const x = 10;",
			"/home/src/workspaces/project/b.ts": "const y = 10;",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "noEmitOnError": true,
        "declaration": true,
        "composite": true,
    },
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption:         "error and enable declarationMap",
		CommandLineArgs: []string{"--declarationMap"},
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/a.ts", "const x: 20 = 10;")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "fix error declarationMap",
		CommandLineArgs: []string{"--declarationMap"},
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/a.ts", "const x = 10;")
		},
	})
	test.End()
}
