// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_noEmit_dts_errors_without_dts_enabled(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "noEmit",
		SubScenario:     "dts errors without dts enabled",
		CommandLineArgs: []string{"--noEmit"},
		Cwd:             "/home/src/projects/project",
		Files: tsctests.FileMap{
			"/home/src/projects/project/a.ts": "const a = class { private p = 10; };",
			"/home/src/projects/project/tsconfig.json": `{
    "compilerOptions": {
        "incremental": false,
        "declaration": false
    }
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Fix error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/projects/project/a.ts", "const a = \"hello\";")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "Emit after fixing error",
		CommandLineArgs: []string{},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Introduce error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/projects/project/a.ts", "const a = class { private p = 10; };")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "Emit when error",
		CommandLineArgs: []string{},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})
	test.End()
}
