// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_showConfig_Default_initialized_TSConfig(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "showConfig",
		SubScenario:     "Default initialized TSConfig",
		CommandLineArgs: []string{"--showConfig"},
	}
	test.Start(t)
	test.End()
}
