// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_showConfig_Show_TSConfig_with_list_compiler_options(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "showConfig",
		SubScenario:     "Show TSConfig with list compiler options",
		CommandLineArgs: []string{"--showConfig", "--types", "jquery,mocha"},
	}
	test.Start(t)
	test.End()
}
