// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_projectReferences_default_setup_was_created_correctly(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "projectReferences",
		SubScenario:     "default setup was created correctly",
		CommandLineArgs: []string{"--p", "primary/tsconfig.json"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/primary/a.ts": "export { };",
			"/home/src/workspaces/project/primary/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "outDir": "bin",
    }
}`,
			"/home/src/workspaces/project/secondary/b.ts": "import * as mod_1 from \"../primary/a\";",
			"/home/src/workspaces/project/secondary/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "outDir": "bin",
    },
    "references": [{
        "path": "../primary"
    }]
}`,
		},
	}
	test.Start(t)
	test.End()
}
