// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_noEmit_changes_composite(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "noEmit",
		SubScenario:     "changes composite",
		CommandLineArgs: []string{},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/src/class.ts": `export class classC {
    prop = 1;
}`,
			"/home/src/workspaces/project/src/directUse.ts": `import { indirectClass } from './indirectClass';
new indirectClass().classC.prop;`,
			"/home/src/workspaces/project/src/indirectClass.ts": `import { classC } from './class';
export class indirectClass {
    classC = new classC();
}`,
			"/home/src/workspaces/project/src/indirectUse.ts": `import { indirectClass } from './indirectClass';
new indirectClass().classC.prop;`,
			"/home/src/workspaces/project/src/noChangeFile.ts": `export function writeLog(s: string) {
}`,
			"/home/src/workspaces/project/src/noChangeFileWithEmitSpecificError.ts": `function someFunc(arguments: boolean, ...rest: any[]) {
}`,
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions":  { "composite": true }
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with noEmit",
		CommandLineArgs: []string{"--noEmit"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with noEmit",
		CommandLineArgs: []string{"--noEmit"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "Introduce error but still noEmit",
		CommandLineArgs: []string{"--noEmit"},
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/class.ts", `export class classC {
    prop1 = 1;
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Fix error and emit",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/class.ts", `export class classC {
    prop = 1;
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with emit",
		CommandLineArgs: []string{},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with noEmit",
		CommandLineArgs: []string{"--noEmit"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with noEmit",
		CommandLineArgs: []string{"--noEmit"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with emit",
		CommandLineArgs: []string{},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "Introduce error and emit",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/class.ts", `export class classC {
    prop1 = 1;
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with emit",
		CommandLineArgs: []string{},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with noEmit",
		CommandLineArgs: []string{"--noEmit"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with noEmit",
		CommandLineArgs: []string{"--noEmit"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with emit",
		CommandLineArgs: []string{},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "Fix error and no emit",
		CommandLineArgs: []string{"--noEmit"},
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/class.ts", `export class classC {
    prop = 1;
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with emit",
		CommandLineArgs: []string{},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with noEmit",
		CommandLineArgs: []string{"--noEmit"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with noEmit",
		CommandLineArgs: []string{"--noEmit"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "No Change run with emit",
		CommandLineArgs: []string{},
	})
	test.End()
}
