// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_incremental_option_changes_with_incremental(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:    "incremental",
		SubScenario: "option changes with incremental",
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/a.ts": "export const a = 10;const aLocal = 10;",
			"/home/src/workspaces/project/b.ts": "export const b = 10;const bLocal = 10;",
			"/home/src/workspaces/project/c.ts": "import { a } from \"./a\";export const c = a;",
			"/home/src/workspaces/project/d.ts": "import { b } from \"./b\";export const d = b;",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "incremental": true,
    }
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption:         "with sourceMap",
		CommandLineArgs: []string{"--sourceMap"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "should re-emit only js so they dont contain sourcemap",
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "with declaration, emit Dts and should not emit js",
		CommandLineArgs: []string{"--declaration"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "with declaration and declarationMap",
		CommandLineArgs: []string{"--declaration", "--declarationMap"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "local change",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/a.ts", "export const a = 10;const aLocal = 100;")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "with declaration and declarationMap",
		CommandLineArgs: []string{"--declaration", "--declarationMap"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "with inlineSourceMap",
		CommandLineArgs: []string{"--inlineSourceMap"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "with sourceMap",
		CommandLineArgs: []string{"--sourceMap"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "emit js files",
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "with declaration and declarationMap",
		CommandLineArgs: []string{"--declaration", "--declarationMap"},
	})

	test.Edit(&tsctests.TestEdit{
		Caption:         "with declaration and declarationMap, should not re-emit",
		CommandLineArgs: []string{"--declaration", "--declarationMap"},
	})
	test.End()
}
