// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_listFilesOnly_loose_file(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "listFilesOnly",
		SubScenario:     "loose file",
		CommandLineArgs: []string{"test.ts", "--listFilesOnly"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/test.ts": "export const x = 1;",
		},
	}
	test.Start(t)
	test.End()
}
