// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_incremental_const_enums_aliased_in_different_file(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "incremental",
		SubScenario:     "const enums aliased in different file",
		CommandLineArgs: []string{"-i", "a.ts", "--tsbuildinfofile", "a.tsbuildinfo"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/a.ts": `import {A} from "./c"
let a = A.ONE`,
			"/home/src/workspaces/project/b.d.ts": "export { AWorker as A } from \"./worker\";",
			"/home/src/workspaces/project/c.ts": `import {A} from "./b"
let b = A.ONE
export {A}`,
			"/home/src/workspaces/project/worker.d.ts": `export const enum AWorker {
    ONE = 1
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "change enum value",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/worker.d.ts", `export const enum AWorker {
    ONE = 2
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "change enum value again",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/worker.d.ts", `export const enum AWorker {
    ONE = 3
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "something else changes in b.d.ts",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/b.d.ts", "export { AWorker as A } from \"./worker\";export const randomThing = 10;")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "something else changes in b.d.ts again",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/b.d.ts", "export { AWorker as A } from \"./worker\";export const randomThing = 10;export const randomThing2 = 10;")
		},
	})
	test.End()
}
