// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_projectReferences_referencing_ambient_const_enum_from_referenced_project_with_preserveConstEnums(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "projectReferences",
		SubScenario:     "referencing ambient const enum from referenced project with preserveConstEnums",
		CommandLineArgs: []string{"--p", "project"},
		Cwd:             "/home/src/workspaces/solution",
		Files: tsctests.FileMap{
			"/home/src/workspaces/solution/project/index.ts": "import { E } from \"../utils\"; E.A;",
			"/home/src/workspaces/solution/project/tsconfig.json": `{
    "compilerOptions": {
        "isolatedModules": true,
    },
    "references": [
        { "path": "../utils" },
    ],
}`,
			"/home/src/workspaces/solution/utils/index.d.ts": "export declare const enum E { A = 1 }",
			"/home/src/workspaces/solution/utils/index.ts":   "export const enum E { A = 1 }",
			"/home/src/workspaces/solution/utils/tsconfig.json": `{
    "compilerOptions": {
        "composite": true,
        "declaration": true,
        "preserveConstEnums": true,
    },
}`,
		},
	}
	test.Start(t)
	test.End()
}
