// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_incremental_when_passing_filename_for_buildinfo_on_commandline(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "incremental",
		SubScenario:     "when passing filename for buildinfo on commandline",
		CommandLineArgs: []string{"--incremental", "--tsBuildInfoFile", ".tsbuildinfo", "--explainFiles"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/src/main.ts": "export const x = 10;",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs"
    },
    "include": [
        "src/**/*.ts"
    ],
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})
	test.End()
}
