// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTsc_showConfig_Show_TSConfig_with_compileOnSave_and_more(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "showConfig",
		SubScenario:     "Show TSConfig with compileOnSave and more",
		CommandLineArgs: []string{"-p", "tsconfig.json", "--showConfig"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/src/index.ts": "export const a = 1;",
			"/home/src/workspaces/project/tsconfig.json": `{
    "compilerOptions": {
        "esModuleInterop": true,
        "target": "es5",
        "module": "commonjs",
        "strict": true
    },
    "compileOnSave": true,
    "exclude": [
        "dist"
    ],
    "files": [],
    "include": [
        "src/*"
    ],
    "references": [
        { "path": "./test" }
    ]
}`,
		},
	}
	test.Start(t)
	test.End()
}
