// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTscWatch_commandLineWatch_watch_handles_file_rapidly_recreated(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLineWatch",
		SubScenario:     "watch handles file rapidly recreated",
		CommandLineArgs: []string{"--watch"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/data.ts":       "export const val = \"original\";",
			"/home/src/workspaces/project/index.ts":      "import { val } from \"./data\";",
			"/home/src/workspaces/project/tsconfig.json": "{}",
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "delete and immediately recreate with new content",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/data.ts", "export const val = \"recreated\";")
		},
	})
	test.End()
}
