// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTscWatch_commandLineWatch_watch_detects_package_json_types_field_edited(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLineWatch",
		SubScenario:     "watch detects package json types field edited",
		CommandLineArgs: []string{"--watch"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/index.ts":                        "import { lib } from \"mylib\";",
			"/home/src/workspaces/project/node_modules/mylib/new.d.ts":     "export declare const lib: string;",
			"/home/src/workspaces/project/node_modules/mylib/old.d.ts":     "export declare const lib: number;",
			"/home/src/workspaces/project/node_modules/mylib/package.json": "{\"name\": \"mylib\", \"types\": \"old.d.ts\"}",
			"/home/src/workspaces/project/tsconfig.json":                   "{}",
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "change package.json types field",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/node_modules/mylib/package.json", "{\"name\": \"mylib\", \"types\": \"new.d.ts\"}")
		},
	})
	test.End()
}
