// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTscWatch_commandLineWatch_watch_skips_build_when_no_files_change(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLineWatch",
		SubScenario:     "watch skips build when no files change",
		CommandLineArgs: []string{"--watch"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/index.ts":      "const x: number = 1;",
			"/home/src/workspaces/project/tsconfig.json": "{}",
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "no change",
	})
	test.End()
}
