// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTscWatch_commandLine_Parse_watch_interval_option_without_tsconfig_json(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLine",
		SubScenario:     "Parse watch interval option without tsconfig.json",
		CommandLineArgs: []string{"-w", "--watchInterval", "1000"},
	}
	test.Start(t)
	test.End()
}
