// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTscWatch_commandLineWatch_watch_rebuilds_when_tsconfig_include_pattern_adds_file(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLineWatch",
		SubScenario:     "watch rebuilds when tsconfig include pattern adds file",
		CommandLineArgs: []string{"--watch"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/index.ts": "const x = 1;",
			"/home/src/workspaces/project/tsconfig.json": `{
	"compilerOptions": {},
	"include": ["*.ts"]
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "widen include pattern to add src dir",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/extra.ts", "export const extra = 2;")
			sys.WriteFile("/home/src/workspaces/project/tsconfig.json", `{
	"compilerOptions": {},
	"include": ["*.ts", "src/**/*.ts"]
}`)
		},
	})
	test.End()
}
