// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTscWatch_commandLineWatch_watch_detects_file_deleted_and_new_file_added_simultaneously(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLineWatch",
		SubScenario:     "watch detects file deleted and new file added simultaneously",
		CommandLineArgs: []string{"--watch"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/a.ts":          "import { b } from \"./b\";",
			"/home/src/workspaces/project/b.ts":          "export const b = 1;",
			"/home/src/workspaces/project/tsconfig.json": "{}",
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "delete b.ts and create c.ts with updated import",
		Edit: func(sys *tsctests.TestSys) {
			sys.Remove("/home/src/workspaces/project/b.ts")
			sys.WriteFile("/home/src/workspaces/project/a.ts", "import { c } from \"./c\";")
			sys.WriteFile("/home/src/workspaces/project/c.ts", "export const c = 2;")
		},
	})
	test.End()
}
