// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTscWatch_commandLineWatch_watch_rebuilds_when_tsconfig_is_touched_but_content_unchanged(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLineWatch",
		SubScenario:     "watch rebuilds when tsconfig is touched but content unchanged",
		CommandLineArgs: []string{"--watch"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/index.ts":      "const x = 1;",
			"/home/src/workspaces/project/tsconfig.json": "{}",
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "touch tsconfig without changing content",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/tsconfig.json", "{}")
		},
	})
	test.End()
}
