// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTscWatch_commandLineWatch_watch_detects_file_added_to_previously_non_existent_include_path(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLineWatch",
		SubScenario:     "watch detects file added to previously non-existent include path",
		CommandLineArgs: []string{"--watch"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/index.ts": "const x = 1;",
			"/home/src/workspaces/project/tsconfig.json": `{
	"compilerOptions": {},
	"include": ["index.ts", "src/**/*.ts"]
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "create src dir with ts file matching include",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/helper.ts", "export const helper = \"added\";")
		},
	})
	test.End()
}
