// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTscWatch_noEmit_semantic_errors(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "noEmit",
		SubScenario:     "semantic errors",
		CommandLineArgs: []string{"-w"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/a.ts": "const a: number = \"hello\"",
			"/home/src/workspaces/project/tsconfig.json": `{
	"compilerOptions": {
            "noEmit": true
	}
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "fix error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/a.ts", "const a = \"hello\";")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "emit after fixing error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/tsconfig.json", `{
	"compilerOptions": {
            
	}
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no emit run after fixing error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/tsconfig.json", `{
	"compilerOptions": {
            "noEmit": true,
            
	}
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "introduce error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/a.ts", "const a: number = \"hello\"")
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "emit when error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/tsconfig.json", `{
	"compilerOptions": {
            
	}
}`)
		},
	})

	test.Edit(&tsctests.TestEdit{
		Caption: "no emit run when error",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/tsconfig.json", `{
	"compilerOptions": {
            "noEmit": true,
            
	}
}`)
		},
	})
	test.End()
}
