// Code generated by tsctests; DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/microsoft/typescript-go/internal/execute/tsctests"
)

func TestTscWatch_commandLineWatch_watch_detects_file_added_in_new_nested_subdirectory(t *testing.T) {
	test := &tsctests.TestSpec{
		Scenario:        "commandLineWatch",
		SubScenario:     "watch detects file added in new nested subdirectory",
		CommandLineArgs: []string{"--watch"},
		Files: tsctests.FileMap{
			"/home/src/workspaces/project/src/a.ts": "export const a = 1;",
			"/home/src/workspaces/project/tsconfig.json": `{
	"compilerOptions": {},
	"include": ["src/**/*.ts"]
}`,
		},
	}
	test.Start(t)

	test.Edit(&tsctests.TestEdit{
		Caption: "create nested dir with ts file",
		Edit: func(sys *tsctests.TestSys) {
			sys.WriteFile("/home/src/workspaces/project/src/deep/nested/util.ts", "export const util = \"nested\";")
		},
	})
	test.End()
}
