package pnp

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
	"github.com/microsoft/typescript-go/internal/repo"
	"github.com/microsoft/typescript-go/internal/tspath"
	"github.com/microsoft/typescript-go/internal/vfs/osvfs"
)

type TestSuite struct {
	Manifest jsontext.Value `json:"manifest"`
	Tests    []TestCase     `json:"tests"`
}

type TestCase struct {
	Imported string `json:"imported"`
	Importer string `json:"importer"`
	Expected string `json:"expected"`
	It       string `json:"it"`
}

func TestLoadPnPManifest(t *testing.T) {
	t.Parallel()
	cases := []struct {
		fileName string
		path     string
		msg      string
	}{
		{"pnp-yarn-v3.cjs", filepath.Join(repo.TestDataPath(), "fixtures", "pnp", "pnp-yarn-v3.cjs"), "Expected to load the .pnp.cjs file generated by Yarn 3"},
		{"pnp-yarn-v4.cjs", filepath.Join(repo.TestDataPath(), "fixtures", "pnp", "pnp-yarn-v4.cjs"), "Expected to load the .pnp.cjs file generated by Yarn 4"},
	}

	for _, tc := range cases {
		t.Run(tc.path, func(t *testing.T) {
			t.Parallel()

			fs := osvfs.FS()
			pnpDataString, err := extractPnpDataStringFromPath(fs, tc.path)
			if err != nil {
				t.Fatalf("failed to parse manifest: %v", err)
			}
			_, err = parseManifestFromData(pnpDataString, tspath.GetDirectoryPath(tc.path))
			if err != nil {
				t.Fatalf("failed to parse manifest: %v", err)
			}
		})
	}
}

func TestResolveUnqualified(t *testing.T) {
	t.Parallel()
	expectationsPath := filepath.Join(repo.TestDataPath(), "fixtures", "pnp", "test-expectations.json")

	content, err := os.ReadFile(expectationsPath)
	if err != nil {
		t.Fatalf("Assertion failed: Expected the expectations to be found: %v", err)
	}

	var suites []TestSuite
	if err = json.Unmarshal(content, &suites); err != nil {
		t.Fatalf("Assertion failed: Expected the expectations to be loaded: %v", err)
	}

	for si := range suites {
		if si != 0 {
			continue
		}
		testSuite := &suites[si]

		rawManifest := &testSuite.Manifest
		manifest, err := parseManifestFromData(rawManifest.String(), "/path/to/project/.pnp.cjs")
		if err != nil {
			t.Fatalf("failed to init pnp manifest: %v", err)
		}

		for _, tc := range testSuite.Tests {
			parent := filepath.Join(tc.Importer, "fooo")
			pnpApi := &PnpApi{fs: osvfs.FS(), url: "/path/to/project/.pnp.cjs", manifest: manifest}

			t.Run(tc.It, func(t *testing.T) {
				t.Parallel()
				res, unqualifiedErr := pnpApi.ResolveToUnqualified(tc.Imported, parent)

				switch {
				case unqualifiedErr == nil && res != "":
					if res != tc.Expected {
						t.Fatalf("'%s': expected resolved path %q, got %q", tc.It, tc.Expected, res)
					}
				}
			})
		}
	}
}

func TestParseSinglePackageName(t *testing.T) {
	t.Parallel()
	pnpApi := &PnpApi{}
	name, _, err := pnpApi.ParseBareIdentifier("pkg")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if name != "pkg" {
		t.Fatalf("expected name %q, got %q", "pkg", name)
	}
}

func TestParseScopedPackageName(t *testing.T) {
	t.Parallel()
	pnpApi := &PnpApi{}
	name, _, err := pnpApi.ParseBareIdentifier("@scope/pkg")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if name != "@scope/pkg" {
		t.Fatalf("expected name %q, got %q", "@scope/pkg", name)
	}
}

func TestParsePackageNameWithLongSubpath(t *testing.T) {
	t.Parallel()
	pnpApi := &PnpApi{}
	name, modulePath, err := pnpApi.ParseBareIdentifier("pkg/a/b/c/index.js")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if name != "pkg" {
		t.Fatalf("expected name %q, got %q", "pkg", name)
	}
	if modulePath != "/a/b/c/index.js" {
		t.Fatalf("expected modulePath=%q, got %q", "a/b/c/index.js", modulePath)
	}
}

func TestParseScopedPackageWithLongSubpath(t *testing.T) {
	t.Parallel()
	pnpApi := &PnpApi{}
	name, modulePath, err := pnpApi.ParseBareIdentifier("@scope/pkg/a/b/c/index.js")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if name != "@scope/pkg" {
		t.Fatalf("expected name %q, got %q", "@scope/pkg", name)
	}
	if modulePath != "/a/b/c/index.js" {
		t.Fatalf("expected modulePath=%q, got %q", "a/b/c/index.js", modulePath)
	}
}
