name: Setup Go
description: Setup Go

inputs:
  go-version:
    default: '>=1.23.0'
  cache-name:
    default: 'cache'

runs:
  using: composite
  steps:
    - name: Install Go
      id: install-go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: Go cache
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        # There is more code downloaded and built than is covered by '**/go.sum',
        # so give each job its own cache to try and not end up sharing the wrong
        # cache between jobs.
        key: ts-setup-go-${{ runner.os }}-${{ steps.install-go.outputs.go-version }}-${{ github.workflow }}-${{ inputs.cache-name }}-${{ hashFiles('**/go.sum', '**/Herebyfile.mjs') }}
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~/AppData/Local/go-build
