name: Setup Go
description: Setup Go

inputs:
  go-version:
    description: Go version to set up in go-install.ps1 format
    default: 'go1.25'

runs:
  using: composite

  steps:
    - name: Install Go
      id: install-go
      shell: pwsh
      run: |
        # https://github.com/microsoft/go-infra/blob/main/goinstallscript/powershell/go-install.ps1
        ${{ github.action_path }}/go-install.ps1 -Version ${{ inputs.go-version }} -GitHubActionsPath

        $goVersionOutput = go version
        Write-Host $goVersionOutput
        # Extract version like "1.23.4" from "go version go1.23.4 windows/amd64"
        if ($goVersionOutput -match 'go version go([\d\.]+)') {
          $exactVersion = $matches[1]
          "go-version=$exactVersion" >> $env:GITHUB_OUTPUT
          Write-Host "Exact Go version: $exactVersion"
        } else {
          Write-Error "Failed to parse Go version from: $goVersionOutput"
          exit 1
        }

    - name: Verify Microsoft Go
      shell: pwsh
      run: |
        $goPath = (Get-Command go).Source
        Write-Host "Go executable path: $goPath"
        if ($goPath -notlike "*microsoft-go*") {
          Write-Error "Go installation is not from microsoft-go. Path: $goPath"
          exit 1
        }
        Write-Host "✓ Verified: Microsoft Go is active"

    - name: Add GOBIN to PATH
      shell: bash
      run: |
        GOBIN=$(go env GOBIN)
        if [ -z "$GOBIN" ]; then
          GOBIN="$(go env GOPATH)/bin"
        fi
        echo "$GOBIN" >> $GITHUB_PATH

    - name: Set mtimes
      shell: bash
      run: |
        find . -type f ! -path ./.git/\*\* | go run github.com/slsyy/mtimehash/cmd/mtimehash@v1.0.0 || true
        find . -type d ! -path ./.git/\*\* -exec touch -d '1970-01-01T00:00:01Z' {} + || true
