name: Setup Go
description: Setup Go

inputs:
  go-version:
    description: Go version range to set up.
    default: '>=1.24.0'
  create:
    description: Create the cache
    default: 'false'

runs:
  using: composite

  steps:
    - name: Install Go
      id: install-go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: Cache Go modules
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        key: go-modules-${{ runner.os }}-${{ steps.install-go.outputs.go-version }}-${{ hashFiles('**/go.sum', '**/Herebyfile.mjs', '**/.custom-gcl.yml') }}
        path: |
          ~/go/pkg/mod

    - if: ${{ inputs.create == 'true' }}
      shell: bash
      run: npm ci

    - name: Set mtimes
      shell: bash
      run: |
        find . -type f ! -path ./.git/\*\* | go run github.com/slsyy/mtimehash/cmd/mtimehash@v1.0.0 || true
        find . -type d ! -path ./.git/\*\* -exec touch -d '1970-01-01T00:00:01Z' {} + || true

    - if: ${{ inputs.create == 'true' }}
      shell: bash
      run: npx hereby build

    - if: ${{ inputs.create == 'true' }}
      shell: bash
      run: npx hereby test

    - if: ${{ inputs.create == 'true' }}
      shell: bash
      run: npx hereby lint

    - if: ${{ inputs.create == 'true' }}
      shell: bash
      run: npx dprint check

    # Avoid hardcoding the cache key more than once.
    - name: Create Go build cache key
      shell: bash
      id: go-build-cache-key
      env:
        CACHE_KEY: go-build-cache-${{ runner.os }}-${{ steps.install-go.outputs.go-version }}
      run: |
        echo "key=$CACHE_KEY" >> $GITHUB_OUTPUT

    - if: ${{ inputs.create == 'true' }}
      name: Save Go build cache
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        # Save a new cache each time by including the unique run ID.
        key: ${{ steps.go-build-cache-key.outputs.key }}-${{ github.run_id }}
        path: |
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~/AppData/Local/go-build

    - if: ${{ inputs.create != 'true' }}
      name: Restore Go build cache
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        # key is unused, but a required input.
        key: ${{ steps.go-build-cache-key.outputs.key }}-
        # Restore the most recent cache, ignoring the run ID.
        restore-keys: ${{ steps.go-build-cache-key.outputs.key }}-
        path: |
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~/AppData/Local/go-build
