name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

# Ensure scripts are run with pipefail. See:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      - uses: ./.github/actions/setup-go
        with:
          cache-name: build

      - run: npm ci

      - run: npx hereby build

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        no-submodules:
          - false
        race:
          - false
        include:
          - os: ubuntu-latest
            no-submodules: true
          - os: ubuntu-latest
            race: true

    name: test (${{ matrix.os }}${{ (matrix.no-submodules && ' without submodules') || '' }}${{ (matrix.race && ' in race mode') || '' }})

    runs-on: ${{ matrix.os }}

    steps:
      - run: git config --system core.longpaths true
        if: ${{ matrix.os == 'windows-latest' }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: ${{ !matrix.no-submodules }}
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      - uses: ./.github/actions/setup-go
        with:
          cache-name: test

      - run: npm ci

      - run: go install gotest.tools/gotestsum@latest
        # Installing gotestsum is super slow on Windows.
        if: ${{ matrix.os != 'windows-latest' }}

      - run: npx hereby test:all
        if: ${{ !matrix.race }}

      - run: npx hereby test:all --race
        if: ${{ matrix.race }}

      - run: git add .
      - run: git diff --staged --exit-code --stat

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      - uses: ./.github/actions/setup-go
        with:
          cache-name: lint

      - run: npm ci

      - run: npx hereby install-tools
      - run: npx hereby lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      - uses: ./.github/actions/setup-go
        with:
          cache-name: format

      - run: npm ci

      - run: npx hereby install-tools
      - run: npx hereby check:format

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      - uses: ./.github/actions/setup-go
        with:
          cache-name: generate

      - run: npm ci

      - run: npx hereby generate

      - run: git add .
      - run: git diff --staged --exit-code --stat

  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup-go
        with:
          cache-name: tidy

      - run: go mod tidy
      - run: go -C ./_tools mod tidy

      - run: git add .
      - run: git diff --staged --exit-code --stat

  required:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - build
      - test
      - lint
      - format
      - generate
      - tidy

    steps:
      - name: Check required jobs
        env:
          NEEDS: ${{ toJson(needs) }}
        run: |
          ! echo $NEEDS | jq -e 'to_entries[] | { job: .key, result: .value.result } | select(.result != "success")'
